// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	_ "github.com/go-playground/validator/v10"
	"provider"
	"time"
)



// MetadataT Contains the metadata of a single CSAF issuing party.
type MetadataT struct {
	// Holds the date and time when this entry was last updated.
	LastUpdated time.Time `json:"last_updated" validate:"required"`
	// Provides information about the issuing party for this entry.
	Publisher PublisherT `json:"publisher" validate:"required"`
	// Contains the role of the issuing party according to section 7 in the CSAF standard.
	Role RoleT `json:"role" validate:"required"`
	// Contains the URL of the provider-metadata.json for that entry.
	Url CanonicalUrlT `json:"url" validate:"required"`
}



// $schema Contains the URL of the Aggregator JSON schema which the document promises to be valid for.
type $schema string

const (
	$schemaHTTPS://DOCS_OASIS_OPEN_ORG/CSAF/CSAF/V2_1/SCHEMA/AGGREGATOR_JSON $schema = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/aggregator.json"
)

// Category Provides information about the category of aggregator.
type Category string

const (
	CategoryAGGREGATOR Category = "aggregator"
	CategoryLISTER Category = "lister"
)

// Aggregator Provides information about the aggregator.
type Aggregator struct {
	// Provides information about the category of aggregator.
	Category Category `json:"category" validate:"required"`
	// Information on how to contact the aggregator, possibly including details such as web sites, email addresses, phone numbers, and postal mail addresses.
	ContactDetails *string `json:"contact_details,omitempty" validate:"min=1"`
	// Provides information about the authority of the aggregator to release the list, in particular, the party's constituency and responsibilities or other obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty" validate:"min=1"`
	// Contains the name of the aggregator.
	Name string `json:"name" validate:"required,min=1"`
	// Contains a URL which is under control of the aggregator and can be used as a globally unique identifier for that aggregator.
	Namespace string `json:"namespace" validate:"required,url"`
}

// AggregatorVersion Gives the version of the CSAF aggregator specification which the document was generated for.
type AggregatorVersion string

const (
	AggregatorVersion2_1 AggregatorVersion = "2.1"
)

// CsafProvidersItem Contains information from a CSAF provider.
type CsafProvidersItem struct {
	// Contains the metadata of a single CSAF provider.
	Metadata MetadataT `json:"metadata" validate:"required"`
	// Contains a list of URLs or mirrors for this CSAF provider.
	Mirrors *MirrorsT `json:"mirrors,omitempty"`
}

// CsafPublishersItem Contains information from a CSAF publisher.
type CsafPublishersItem struct {
	// Contains the metadata of a single CSAF publisher extracted from one of its CSAF documents.
	Metadata MetadataT `json:"metadata" validate:"required"`
	// Contains a list of URLs or mirrors for this CSAF publisher.
	Mirrors MirrorsT `json:"mirrors" validate:"required"`
	// Contains information about how often the CSAF publisher is checked for new CSAF documents.
	UpdateInterval string `json:"update_interval" validate:"required,min=1"`
}

// CSAFAggregator Representation of information where to find CSAF providers as a JSON document.
type CSAFAggregator struct {
	// Contains the URL of the Aggregator JSON schema which the document promises to be valid for.
	FSchema $schema `json:"$schema" validate:"required"`
	// Provides information about the aggregator.
	Aggregator Aggregator `json:"aggregator" validate:"required"`
	// Gives the version of the CSAF aggregator specification which the document was generated for.
	AggregatorVersion AggregatorVersion `json:"aggregator_version" validate:"required"`
	// Contains the URL for this document.
	CanonicalUrl AggregatorUrlT `json:"canonical_url" validate:"required"`
	// Contains a list with information from CSAF providers.
	CsafProviders []CsafProvidersItem `json:"csaf_providers" validate:"required,min=1"`
	// Contains a list with information from CSAF publishers.
	CsafPublishers *[]CsafPublishersItem `json:"csaf_publishers,omitempty" validate:"min=1"`
	// Holds the date and time when the document was last updated.
	LastUpdated time.Time `json:"last_updated" validate:"required"`
	// Holds the date and time from when this CSAF aggregator file is in a maintained state.
	MaintainedFrom *time.Time `json:"maintained_from,omitempty"`
	// Holds the date and time until when this CSAF aggregator file is in a maintained state.
	MaintainedUntil *time.Time `json:"maintained_until,omitempty"`
}