// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	_ "github.com/go-playground/validator/v10"
)



type Schema struct {
	Core
	Applicator
	Unevaluated
	Validation
	MetaData
	FormatAssertion
}

// $schema3 Contains the definition of the object of the CSAF Extension JSON schema which the JSON object promises to be valid for.
type $schema3 struct {
	// Contains the actual value of the $schema property.
	Const *ContentSchemaT `json:"const,omitempty"`
	// Contains the description for the CSAF Extension $schema value.
	Description string `json:"description" validate:"required,min=1"`
	// Contains the format of the $schema value which is `uri`.
	Format string `json:"format" validate:"required,oneof=uri"`
	// Contains the pattern for value of the $schema property.
	Pattern *string `json:"pattern,omitempty" validate:"oneof=^(?!https:\\/\\/docs\\.oasis-open\\.org\\/csaf\\/csaf\\/v2\\.1\\/([^\\/\\s]+/)*schema\\/extension-content\\.json)(https:\\/\\/[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?(\\.[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?)+\\/([^\\/\\s]+/)*[^\\/\\s]+_(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\\.json)$"`
	// Contains the title for the CSAF Extension $schema.
	Title string `json:"title" validate:"required,min=1"`
	// Contains the type of the $schema value which is `string`.
	Type string `json:"type" validate:"required,oneof=string"`
}

type EnumItem string

const (
	EnumItemESSENTIAL EnumItem = "essential"
	EnumItemSIGNIFICANT EnumItem = "significant"
	EnumItemSUPPLEMENTARY EnumItem = "supplementary"
)

// Category8 Contains the definition of the object of the CSAF Extension Category.
type Category8 struct {
	// Contains the description for the CSAF Extension category value.
	Description string `json:"description" validate:"required,min=1"`
	// Contains the possible options for the category.
	Enum []EnumItem `json:"enum" validate:"required,min=1,max=3"`
	// Contains the title for the CSAF Extension category.
	Title string `json:"title" validate:"required,min=1"`
	// Contains the type of the category value which is `string`.
	Type string `json:"type" validate:"required,oneof=string"`
}

// Const Contains the only allowed value of the critical value as defined by the CSAF Extension Schema - either `true` or `false`.
type Const any

var ConstValues = []Const{
	false,
	true,
}

// Default Contains the default of the critical value - either `true` or `false`.
type Default string

const (
	DefaultFALSE Default = "false"
	DefaultTRUE Default = "true"
)

// Critical Contains the definition of the object of the CSAF Extension critical.
type Critical struct {
	// Contains the only allowed value of the critical value as defined by the CSAF Extension Schema - either `true` or `false`.
	Const *Const `json:"const,omitempty"`
	// Contains the default of the critical value - either `true` or `false`.
	Default *Default `json:"default,omitempty"`
	// Contains the description for the CSAF Extension critical value.
	Description string `json:"description" validate:"required,min=1"`
	// Contains the title for the CSAF Extension critical.
	Title string `json:"title" validate:"required,min=1"`
	// Contains the type of the critical value which is `boolean`.
	Type string `json:"type" validate:"required,oneof=boolean"`
}

// Properties Contains the definition of the properties a CSAF Extension Schema needs.
type Properties struct {
	// Contains the definition of the object of the CSAF Extension JSON schema which the JSON object promises to be valid for.
	FSchema $schema3 `json:"$schema" validate:"required"`
	// Contains the definition of the object of the CSAF Extension Category.
	Category Category8 `json:"category" validate:"required"`
	// Contains the definition of the object of the CSAF Extension content.
	Content Schema `json:"content" validate:"required"`
	// Contains the definition of the object of the CSAF Extension critical.
	Critical Critical `json:"critical" validate:"required"`
}

// CSAFExtensionMetaschema Representation of a CSAF Extension Schema
type CSAFExtensionMetaschema struct {
	// Contains the URL of the CSAF Extension Metaschema JSON schema which the JSON schema promises to be valid for.
	FSchema string `json:"$schema" validate:"required,oneof=https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json"`
	// Contains the ID as URL of the CSAF Extension JSON schema which identifies the CSAF Extension Schema.
	FId ContentSchemaT `json:"$id" validate:"required"`
	// Contains the title for the CSAF Extension Schema.
	Title string `json:"title" validate:"required,min=1"`
	// Contains the description for the CSAF Extension Schema detailing what the CSAF Extension is about.
	Description string `json:"description" validate:"required,min=1"`
	// Contains the type of the CSAF Extension Schema which is always `object`.
	Type string `json:"type" validate:"required,oneof=object"`
	// Contains the definitions as object of the CSAF Extension Schema.
	FDefs *Schema `json:"$defs,omitempty"`
	// Contains the list of required properties.
	Required any `json:"required" validate:"required"`
	// Contains the definition of the properties a CSAF Extension Schema needs.
	Properties Properties `json:"properties" validate:"required"`
	// Prohibits additional properties on this level.
	AdditionalProperties any `json:"additionalProperties" validate:"required"`
}