// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	"extension-metaschema"
	_ "github.com/go-playground/validator/v10"
)

// Category7 Holds the category of the extension content.
type Category7 string

const (
	Category7ESSENTIAL     Category7 = "essential"
	Category7SIGNIFICANT   Category7 = "significant"
	Category7SUPPLEMENTARY Category7 = "supplementary"
)

// CSAFExtensionContent Representation of additional information extending a CSAF Document.
type CSAFExtensionContent struct {
	// Contains the URL of the CSAF Extension JSON schema which the JSON object promises to be valid for.
	FSchema ContentSchemaT `json:"$schema" validate:"required"`
	// Holds the category of the extension content.
	Category Category7 `json:"category" validate:"required"`
	// Contains the additional information in its properties.
	Content map[string]any `json:"content" validate:"required"`
	// Determines whether using the extension would fail a mandatory test.
	Critical bool `json:"critical" validate:"required"`
}
