// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	"extension-metaschema"
	_ "github.com/go-playground/validator/v10"
	"time"
)

// LocationT Contains all necessary information for a single location.
type LocationT struct {
	// Contains the number how often the extension can be present in this path.
	MaxOccurrence int `json:"max_occurrence" validate:"required,gte=0"`
}

// Requirement Contains the requirement for all possible paths.
type Requirement struct {
	// Contains requirements for this extension on document path.
	FDocumentXExtensions LocationT `json:"$.document.x_extensions" validate:"required"`
	// Contains requirements for this extension on the Product Tree Branch path.
	FProductTreeBranchesProductXExtensions LocationT `json:"$.product_tree.branches..product.x_extensions" validate:"required"`
	// Contains requirements for this extension on the Product Tree Full Product Names path.
	FProductTreeFullProductNamesXExtensions LocationT `json:"$.product_tree.full_product_names[*].x_extensions" validate:"required"`
	// Contains requirements for this extension on the Product Tree Relationships path.
	FProductTreeRelationshipsFullProductNameXExtensions LocationT `json:"$.product_tree.relationships[*].full_product_name.x_extensions" validate:"required"`
	// Contains requirements for this extension on the Vulnerabilities Metrics path.
	FVulnerabilitiesMetricsContentXExtensions LocationT `json:"$.vulnerabilities[*].metrics[*].content.x_extensions" validate:"required"`
	// Contains requirements for this extension on the Vulnerabilities path.
	FVulnerabilitiesXExtensions LocationT `json:"$.vulnerabilities[*].x_extensions" validate:"required"`
	// Contains requirements for this extension on the root path.
	FXExtensions LocationT `json:"$.x_extensions" validate:"required"`
}

// CSAFExtensionMetadata Representation of metadata for a CSAF Extension.
type CSAFExtensionMetadata struct {
	// Contains the URL of the CSAF Extension Metadata JSON schema which the JSON object promises to be valid for.
	FSchema string `json:"$schema" validate:"required,oneof=https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metadata.json"`
	// Holds the `$id` value of the CSAF Extension Schema this metadata applies to.
	ExtensionSchema ContentSchemaT `json:"extension_schema" validate:"required"`
	// Contains a list of incompatible extensions.
	IncompatibleExtensions *[]ContentSchemaT `json:"incompatible_extensions,omitempty" validate:"min=1"`
	// Holds the date and time when the document was last updated.
	LastUpdated time.Time `json:"last_updated" validate:"required"`
	// Contains the requirement for all possible paths.
	Requirement Requirement `json:"requirement" validate:"required"`
}
