// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	"csaf"
)

type Meta struct {
	Core
	Applicator
	Unevaluated
	Validation
	MetaData
	FormatAssertion
	Content
}
