// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:40Z

package comparison

import (
	_ "github.com/go-playground/validator/v10"
	"time"
)







// Category9 Provides information about the category of publisher releasing the document.
type Category9 string

const (
	Category9COORDINATOR Category9 = "coordinator"
	Category9DISCOVERER Category9 = "discoverer"
	Category9MULTIPLIER Category9 = "multiplier"
	Category9OTHER Category9 = "other"
	Category9TRANSLATOR Category9 = "translator"
	Category9USER Category9 = "user"
	Category9VENDOR Category9 = "vendor"
)

// Contact2 Contains information on how to contact the publisher.
type Contact2 struct {
	// Contains details regarding ways to reach the publisher, e.g. through web sites, phone numbers, and postal mail addresses.
	Details *string `json:"details,omitempty" validate:"min=1"`
	// Contains the email address that can be used to reach the issuing party.
	Email *string `json:"email,omitempty" validate:"min=6,email"`
	// Contains a URL pointing to a public OpenPGP key valid for the email of issuing party provided in the sibling property `email`.
	PublicOpenpgpKeyUrl *string `json:"public_openpgp_key_url,omitempty" validate:"min=11,url"`
}

// PublisherT Provides information about the publisher of the document.
type PublisherT struct {
	// Provides information about the category of publisher releasing the document.
	Category Category9 `json:"category" validate:"required"`
	// Contains information on how to contact the publisher.
	Contact *Contact2 `json:"contact,omitempty"`
	// Provides information about the authority of the issuing party to release the document, in particular, the party's constituency and responsibilities or other obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty" validate:"min=1"`
	// Contains the name of the issuing party.
	Name string `json:"name" validate:"required,min=1"`
	// Contains a URL which is under control of the issuing party and can be used as a globally unique identifier for that issuing party.
	Namespace string `json:"namespace" validate:"required,url"`
}

// TlpLabelT Provides the TLP label of the document.
type TlpLabelT string

const (
	TlpLabelTAMBER TlpLabelT = "AMBER"
	TlpLabelTAMBER+STRICT TlpLabelT = "AMBER+STRICT"
	TlpLabelTCLEAR TlpLabelT = "CLEAR"
	TlpLabelTGREEN TlpLabelT = "GREEN"
	TlpLabelTRED TlpLabelT = "RED"
)

// RoleT Contains the role of the issuing party according to section 7 in the CSAF standard.
type RoleT string

const (
	RoleTCSAF_PUBLISHER RoleT = "csaf_publisher"
	RoleTCSAF_PROVIDER RoleT = "csaf_provider"
	RoleTCSAF_TRUSTED_PROVIDER RoleT = "csaf_trusted_provider"
)

// $schema4 Contains the URL of the provider-metadata.json JSON schema which the document promises to be valid for.
type $schema4 string

const (
	$schema4HTTPS://DOCS_OASIS_OPEN_ORG/CSAF/CSAF/V2_1/SCHEMA/PROVIDER_JSON $schema4 = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/provider.json"
)

// Directory Contains all information for directory-based distribution.
type Directory struct {
	// Provides the TLP label for the directory.
	TlpLabel TlpLabelT `json:"tlp_label" validate:"required"`
	// Contains the base url for the directory-based distribution.
	Url UrlT `json:"url" validate:"required"`
}

// FeedsItem Contains information about the ROLIE feed.
type FeedsItem struct {
	// Holds the date and time when the feed was last updated.
	LastUpdated time.Time `json:"last_updated" validate:"required"`
	// Contains a summary of the feed.
	Summary *string `json:"summary,omitempty"`
	// Provides the TLP label for the feed.
	TlpLabel TlpLabelT `json:"tlp_label" validate:"required"`
	// Contains the URL of the feed.
	Url JsonUrlT `json:"url" validate:"required"`
}

// Rolie Contains all information for ROLIE distribution.
type Rolie struct {
	// Contains a list of URLs which contain ROLIE category documents.
	Categories *[]JsonUrlT `json:"categories,omitempty" validate:"min=1"`
	// Contains a list of information about ROLIE feeds.
	Feeds []FeedsItem `json:"feeds" validate:"required,min=1"`
	// Contains a list of URLs which contain ROLIE service documents.
	Services *[]JsonUrlT `json:"services,omitempty" validate:"min=1"`
}

// DistributionsItem Contains the information of a used distribution mechanism.
type DistributionsItem struct {
	// Contains all information for directory-based distribution.
	Directory *Directory `json:"directory,omitempty"`
	// Contains all information for ROLIE distribution.
	Rolie *Rolie `json:"rolie,omitempty"`
}

// MetadataVersion Gives the version of the CSAF provider metadata specification which the document was generated for.
type MetadataVersion string

const (
	MetadataVersion2_1 MetadataVersion = "2.1"
)

// PublicOpenpgpKeysItem Contains all information about an OpenPGP key used to sign CSAF documents.
type PublicOpenpgpKeysItem struct {
	// Contains the fingerprint of the OpenPGP key.
	Fingerprint string `json:"fingerprint" validate:"required,min=40"`
	// Contains the URL where the key can be retrieved.
	Url UrlT `json:"url" validate:"required"`
}

// Role Contains the role of the issuing party according to section 7 in the CSAF standard.
type Role string

const (
	RoleCSAF_PUBLISHER Role = "csaf_publisher"
	RoleCSAF_PROVIDER Role = "csaf_provider"
	RoleCSAF_TRUSTED_PROVIDER Role = "csaf_trusted_provider"
)

// CSAFProviderMetadata Representation of metadata information of a CSAF provider as a JSON document.
type CSAFProviderMetadata struct {
	// Contains the URL of the provider-metadata.json JSON schema which the document promises to be valid for.
	FSchema $schema4 `json:"$schema" validate:"required"`
	// Contains the URL for this document.
	CanonicalUrl ProviderUrlT `json:"canonical_url" validate:"required"`
	// Contains a list of used distribution mechanisms.
	Distributions *[]DistributionsItem `json:"distributions,omitempty" validate:"min=1"`
	// Holds the date and time when the document was last updated.
	LastUpdated time.Time `json:"last_updated" validate:"required"`
	// Decides whether this file should be linked in the list of a CSAF aggregator.
	ListOnCSAFAggregators bool `json:"list_on_CSAF_aggregators" validate:"required"`
	// Holds the date and time from when the distributions within this CSAF provider are in a maintained state.
	MaintainedFrom *time.Time `json:"maintained_from,omitempty"`
	// Holds the date and time until when the distributions within this CSAF provider are in a maintained state.
	MaintainedUntil *time.Time `json:"maintained_until,omitempty"`
	// Gives the version of the CSAF provider metadata specification which the document was generated for.
	MetadataVersion MetadataVersion `json:"metadata_version" validate:"required"`
	// Decides whether the CSAF documents can be mirrored and provided by a CSAF aggregator.
	MirrorOnCSAFAggregators bool `json:"mirror_on_CSAF_aggregators" validate:"required"`
	// Contains a list of OpenPGP keys used to sign CSAF documents.
	PublicOpenpgpKeys *[]PublicOpenpgpKeysItem `json:"public_openpgp_keys,omitempty"`
	// Provides information about the publisher of the CSAF documents in this repository.
	Publisher PublisherT `json:"publisher" validate:"required"`
	// Contains the role of the issuing party according to section 7 in the CSAF standard.
	Role Role `json:"role" validate:"required"`
}