// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

type AccessComplexityType string

const AccessComplexityTypeHIGH AccessComplexityType = "HIGH"
const AccessComplexityTypeLOW AccessComplexityType = "LOW"
const AccessComplexityTypeMEDIUM AccessComplexityType = "MEDIUM"

type AccessVectorType string

const AccessVectorTypeADJACENTNETWORK AccessVectorType = "ADJACENT_NETWORK"
const AccessVectorTypeLOCAL AccessVectorType = "LOCAL"
const AccessVectorTypeNETWORK AccessVectorType = "NETWORK"

type AttackComplexityType string

const AttackComplexityTypeHIGH AttackComplexityType = "HIGH"
const AttackComplexityTypeLOW AttackComplexityType = "LOW"

type AttackRequirementsType string

const AttackRequirementsTypeNONE AttackRequirementsType = "NONE"
const AttackRequirementsTypePRESENT AttackRequirementsType = "PRESENT"

type AttackVectorType string

const AttackVectorTypeADJACENT AttackVectorType = "ADJACENT"
const AttackVectorTypeLOCAL AttackVectorType = "LOCAL"
const AttackVectorTypeNETWORK AttackVectorType = "NETWORK"
const AttackVectorTypePHYSICAL AttackVectorType = "PHYSICAL"

type AttackVectorType_1 string

const AttackVectorType_1_ADJACENTNETWORK AttackVectorType_1 = "ADJACENT_NETWORK"
const AttackVectorType_1_LOCAL AttackVectorType_1 = "LOCAL"
const AttackVectorType_1_NETWORK AttackVectorType_1 = "NETWORK"
const AttackVectorType_1_PHYSICAL AttackVectorType_1 = "PHYSICAL"

type AuthenticationType string

const AuthenticationTypeMULTIPLE AuthenticationType = "MULTIPLE"
const AuthenticationTypeNONE AuthenticationType = "NONE"
const AuthenticationTypeSINGLE AuthenticationType = "SINGLE"

type AutomatableType string

const AutomatableTypeNO AutomatableType = "NO"
const AutomatableTypeNOTDEFINED AutomatableType = "NOT_DEFINED"
const AutomatableTypeYES AutomatableType = "YES"

type CVSSV20 struct {
	// AccessComplexity corresponds to the JSON schema field "accessComplexity".
	AccessComplexity *AccessComplexityType `json:"accessComplexity,omitempty,omitzero"`

	// AccessVector corresponds to the JSON schema field "accessVector".
	AccessVector *AccessVectorType `json:"accessVector,omitempty,omitzero"`

	// Authentication corresponds to the JSON schema field "authentication".
	Authentication *AuthenticationType `json:"authentication,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// CollateralDamagePotential corresponds to the JSON schema field
	// "collateralDamagePotential".
	CollateralDamagePotential *CollateralDamagePotentialType `json:"collateralDamagePotential,omitempty,omitzero"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// Exploitability corresponds to the JSON schema field "exploitability".
	Exploitability *ExploitabilityType `json:"exploitability,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ReportConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// TargetDistribution corresponds to the JSON schema field "targetDistribution".
	TargetDistribution *TargetDistributionType `json:"targetDistribution,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV20Version `json:"version"`
}

type CVSSV20Version string

const CVSSV20VersionA20 CVSSV20Version = "2.0"

type CVSSV30 struct {
	// AttackComplexity corresponds to the JSON schema field "attackComplexity".
	AttackComplexity *AttackComplexityType `json:"attackComplexity,omitempty,omitzero"`

	// AttackVector corresponds to the JSON schema field "attackVector".
	AttackVector *AttackVectorType_1 `json:"attackVector,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType_1 `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity SeverityType `json:"baseSeverity"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType_1 `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// EnvironmentalSeverity corresponds to the JSON schema field
	// "environmentalSeverity".
	EnvironmentalSeverity *SeverityType `json:"environmentalSeverity,omitempty,omitzero"`

	// ExploitCodeMaturity corresponds to the JSON schema field "exploitCodeMaturity".
	ExploitCodeMaturity *ExploitCodeMaturityType `json:"exploitCodeMaturity,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType_1 `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// ModifiedAttackComplexity corresponds to the JSON schema field
	// "modifiedAttackComplexity".
	ModifiedAttackComplexity *ModifiedAttackComplexityType_1 `json:"modifiedAttackComplexity,omitempty,omitzero"`

	// ModifiedAttackVector corresponds to the JSON schema field
	// "modifiedAttackVector".
	ModifiedAttackVector *ModifiedAttackVectorType_1 `json:"modifiedAttackVector,omitempty,omitzero"`

	// ModifiedAvailabilityImpact corresponds to the JSON schema field
	// "modifiedAvailabilityImpact".
	ModifiedAvailabilityImpact *ModifiedCiaType `json:"modifiedAvailabilityImpact,omitempty,omitzero"`

	// ModifiedConfidentialityImpact corresponds to the JSON schema field
	// "modifiedConfidentialityImpact".
	ModifiedConfidentialityImpact *ModifiedCiaType `json:"modifiedConfidentialityImpact,omitempty,omitzero"`

	// ModifiedIntegrityImpact corresponds to the JSON schema field
	// "modifiedIntegrityImpact".
	ModifiedIntegrityImpact *ModifiedCiaType `json:"modifiedIntegrityImpact,omitempty,omitzero"`

	// ModifiedPrivilegesRequired corresponds to the JSON schema field
	// "modifiedPrivilegesRequired".
	ModifiedPrivilegesRequired *ModifiedPrivilegesRequiredType_1 `json:"modifiedPrivilegesRequired,omitempty,omitzero"`

	// ModifiedScope corresponds to the JSON schema field "modifiedScope".
	ModifiedScope *ModifiedScopeType `json:"modifiedScope,omitempty,omitzero"`

	// ModifiedUserInteraction corresponds to the JSON schema field
	// "modifiedUserInteraction".
	ModifiedUserInteraction *ModifiedUserInteractionType_1 `json:"modifiedUserInteraction,omitempty,omitzero"`

	// PrivilegesRequired corresponds to the JSON schema field "privilegesRequired".
	PrivilegesRequired *PrivilegesRequiredType `json:"privilegesRequired,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// Scope corresponds to the JSON schema field "scope".
	Scope *ScopeType `json:"scope,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// TemporalSeverity corresponds to the JSON schema field "temporalSeverity".
	TemporalSeverity *SeverityType `json:"temporalSeverity,omitempty,omitzero"`

	// UserInteraction corresponds to the JSON schema field "userInteraction".
	UserInteraction *UserInteractionType_1 `json:"userInteraction,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV30Version `json:"version"`
}

type CVSSV30Version string

const CVSSV30VersionA30 CVSSV30Version = "3.0"

type CVSSV31 struct {
	// AttackComplexity corresponds to the JSON schema field "attackComplexity".
	AttackComplexity *AttackComplexityType `json:"attackComplexity,omitempty,omitzero"`

	// AttackVector corresponds to the JSON schema field "attackVector".
	AttackVector *AttackVectorType_1 `json:"attackVector,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType_1 `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity SeverityType `json:"baseSeverity"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType_1 `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// EnvironmentalSeverity corresponds to the JSON schema field
	// "environmentalSeverity".
	EnvironmentalSeverity *SeverityType `json:"environmentalSeverity,omitempty,omitzero"`

	// ExploitCodeMaturity corresponds to the JSON schema field "exploitCodeMaturity".
	ExploitCodeMaturity *ExploitCodeMaturityType `json:"exploitCodeMaturity,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType_1 `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// ModifiedAttackComplexity corresponds to the JSON schema field
	// "modifiedAttackComplexity".
	ModifiedAttackComplexity *ModifiedAttackComplexityType_1 `json:"modifiedAttackComplexity,omitempty,omitzero"`

	// ModifiedAttackVector corresponds to the JSON schema field
	// "modifiedAttackVector".
	ModifiedAttackVector *ModifiedAttackVectorType_1 `json:"modifiedAttackVector,omitempty,omitzero"`

	// ModifiedAvailabilityImpact corresponds to the JSON schema field
	// "modifiedAvailabilityImpact".
	ModifiedAvailabilityImpact *ModifiedCiaType `json:"modifiedAvailabilityImpact,omitempty,omitzero"`

	// ModifiedConfidentialityImpact corresponds to the JSON schema field
	// "modifiedConfidentialityImpact".
	ModifiedConfidentialityImpact *ModifiedCiaType `json:"modifiedConfidentialityImpact,omitempty,omitzero"`

	// ModifiedIntegrityImpact corresponds to the JSON schema field
	// "modifiedIntegrityImpact".
	ModifiedIntegrityImpact *ModifiedCiaType `json:"modifiedIntegrityImpact,omitempty,omitzero"`

	// ModifiedPrivilegesRequired corresponds to the JSON schema field
	// "modifiedPrivilegesRequired".
	ModifiedPrivilegesRequired *ModifiedPrivilegesRequiredType_1 `json:"modifiedPrivilegesRequired,omitempty,omitzero"`

	// ModifiedScope corresponds to the JSON schema field "modifiedScope".
	ModifiedScope *ModifiedScopeType `json:"modifiedScope,omitempty,omitzero"`

	// ModifiedUserInteraction corresponds to the JSON schema field
	// "modifiedUserInteraction".
	ModifiedUserInteraction *ModifiedUserInteractionType_1 `json:"modifiedUserInteraction,omitempty,omitzero"`

	// PrivilegesRequired corresponds to the JSON schema field "privilegesRequired".
	PrivilegesRequired *PrivilegesRequiredType `json:"privilegesRequired,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// Scope corresponds to the JSON schema field "scope".
	Scope *ScopeType `json:"scope,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// TemporalSeverity corresponds to the JSON schema field "temporalSeverity".
	TemporalSeverity *SeverityType `json:"temporalSeverity,omitempty,omitzero"`

	// UserInteraction corresponds to the JSON schema field "userInteraction".
	UserInteraction *UserInteractionType_1 `json:"userInteraction,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV31Version `json:"version"`
}

type CVSSV31Version string

const CVSSV31VersionA31 CVSSV31Version = "3.1"

type CVSSV40 struct {
	// Automatable corresponds to the JSON schema field "Automatable".
	Automatable *AutomatableType `json:"Automatable,omitempty,omitzero"`

	// Recovery corresponds to the JSON schema field "Recovery".
	Recovery *RecoveryType `json:"Recovery,omitempty,omitzero"`

	// Safety corresponds to the JSON schema field "Safety".
	Safety *SafetyType `json:"Safety,omitempty,omitzero"`

	// AttackComplexity corresponds to the JSON schema field "attackComplexity".
	AttackComplexity *AttackComplexityType `json:"attackComplexity,omitempty,omitzero"`

	// AttackRequirements corresponds to the JSON schema field "attackRequirements".
	AttackRequirements *AttackRequirementsType `json:"attackRequirements,omitempty,omitzero"`

	// AttackVector corresponds to the JSON schema field "attackVector".
	AttackVector *AttackVectorType `json:"attackVector,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType_1 `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore float64 `json:"baseScore"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity CVSSV40Severity `json:"baseSeverity"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType_1 `json:"confidentialityRequirement,omitempty,omitzero"`

	// ExploitMaturity corresponds to the JSON schema field "exploitMaturity".
	ExploitMaturity *ExploitMaturityType `json:"exploitMaturity,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType_1 `json:"integrityRequirement,omitempty,omitzero"`

	// ModifiedAttackComplexity corresponds to the JSON schema field
	// "modifiedAttackComplexity".
	ModifiedAttackComplexity *ModifiedAttackComplexityType `json:"modifiedAttackComplexity,omitempty,omitzero"`

	// ModifiedAttackRequirements corresponds to the JSON schema field
	// "modifiedAttackRequirements".
	ModifiedAttackRequirements *ModifiedAttackRequirementsType `json:"modifiedAttackRequirements,omitempty,omitzero"`

	// ModifiedAttackVector corresponds to the JSON schema field
	// "modifiedAttackVector".
	ModifiedAttackVector *ModifiedAttackVectorType `json:"modifiedAttackVector,omitempty,omitzero"`

	// ModifiedPrivilegesRequired corresponds to the JSON schema field
	// "modifiedPrivilegesRequired".
	ModifiedPrivilegesRequired *ModifiedPrivilegesRequiredType `json:"modifiedPrivilegesRequired,omitempty,omitzero"`

	// ModifiedSubAvailabilityImpact corresponds to the JSON schema field
	// "modifiedSubAvailabilityImpact".
	ModifiedSubAvailabilityImpact *ModifiedSubIaType `json:"modifiedSubAvailabilityImpact,omitempty,omitzero"`

	// ModifiedSubConfidentialityImpact corresponds to the JSON schema field
	// "modifiedSubConfidentialityImpact".
	ModifiedSubConfidentialityImpact *ModifiedSubCType `json:"modifiedSubConfidentialityImpact,omitempty,omitzero"`

	// ModifiedSubIntegrityImpact corresponds to the JSON schema field
	// "modifiedSubIntegrityImpact".
	ModifiedSubIntegrityImpact *ModifiedSubIaType `json:"modifiedSubIntegrityImpact,omitempty,omitzero"`

	// ModifiedUserInteraction corresponds to the JSON schema field
	// "modifiedUserInteraction".
	ModifiedUserInteraction *ModifiedUserInteractionType `json:"modifiedUserInteraction,omitempty,omitzero"`

	// ModifiedVulnAvailabilityImpact corresponds to the JSON schema field
	// "modifiedVulnAvailabilityImpact".
	ModifiedVulnAvailabilityImpact *ModifiedVulnCiaType `json:"modifiedVulnAvailabilityImpact,omitempty,omitzero"`

	// ModifiedVulnConfidentialityImpact corresponds to the JSON schema field
	// "modifiedVulnConfidentialityImpact".
	ModifiedVulnConfidentialityImpact *ModifiedVulnCiaType `json:"modifiedVulnConfidentialityImpact,omitempty,omitzero"`

	// ModifiedVulnIntegrityImpact corresponds to the JSON schema field
	// "modifiedVulnIntegrityImpact".
	ModifiedVulnIntegrityImpact *ModifiedVulnCiaType `json:"modifiedVulnIntegrityImpact,omitempty,omitzero"`

	// PrivilegesRequired corresponds to the JSON schema field "privilegesRequired".
	PrivilegesRequired *PrivilegesRequiredType `json:"privilegesRequired,omitempty,omitzero"`

	// ProviderUrgency corresponds to the JSON schema field "providerUrgency".
	ProviderUrgency *ProviderUrgencyType `json:"providerUrgency,omitempty,omitzero"`

	// SubAvailabilityImpact corresponds to the JSON schema field
	// "subAvailabilityImpact".
	SubAvailabilityImpact *SubCiaType `json:"subAvailabilityImpact,omitempty,omitzero"`

	// SubConfidentialityImpact corresponds to the JSON schema field
	// "subConfidentialityImpact".
	SubConfidentialityImpact *SubCiaType `json:"subConfidentialityImpact,omitempty,omitzero"`

	// SubIntegrityImpact corresponds to the JSON schema field "subIntegrityImpact".
	SubIntegrityImpact *SubCiaType `json:"subIntegrityImpact,omitempty,omitzero"`

	// UserInteraction corresponds to the JSON schema field "userInteraction".
	UserInteraction *UserInteractionType `json:"userInteraction,omitempty,omitzero"`

	// ValueDensity corresponds to the JSON schema field "valueDensity".
	ValueDensity *ValueDensityType `json:"valueDensity,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV40Version `json:"version"`

	// VulnAvailabilityImpact corresponds to the JSON schema field
	// "vulnAvailabilityImpact".
	VulnAvailabilityImpact *VulnCiaType `json:"vulnAvailabilityImpact,omitempty,omitzero"`

	// VulnConfidentialityImpact corresponds to the JSON schema field
	// "vulnConfidentialityImpact".
	VulnConfidentialityImpact *VulnCiaType `json:"vulnConfidentialityImpact,omitempty,omitzero"`

	// VulnIntegrityImpact corresponds to the JSON schema field "vulnIntegrityImpact".
	VulnIntegrityImpact *VulnCiaType `json:"vulnIntegrityImpact,omitempty,omitzero"`

	// VulnerabilityResponseEffort corresponds to the JSON schema field
	// "vulnerabilityResponseEffort".
	VulnerabilityResponseEffort *VulnerabilityResponseEffortType `json:"vulnerabilityResponseEffort,omitempty,omitzero"`
}

type CVSSV40Version string

const CVSSV40VersionA40 CVSSV40Version = "4.0"

type CVSSV40_0 struct {
	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore *NoneScoreType `json:"baseScore,omitempty,omitzero"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity NoneSeverityType `json:"baseSeverity,omitempty,omitzero"`
}

type CVSSV40_1 struct {
	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore *LowScoreType `json:"baseScore,omitempty,omitzero"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity LowSeverityType `json:"baseSeverity,omitempty,omitzero"`
}

type CVSSV40_2 struct {
	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore *MediumScoreType `json:"baseScore,omitempty,omitzero"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity MediumSeverityType `json:"baseSeverity,omitempty,omitzero"`
}

type CVSSV40_3 struct {
	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore *HighScoreType `json:"baseScore,omitempty,omitzero"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity HighSeverityType `json:"baseSeverity,omitempty,omitzero"`
}

type CVSSV40_4 struct {
	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore *CriticalScoreType `json:"baseScore,omitempty,omitzero"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity CriticalSeverityType `json:"baseSeverity,omitempty,omitzero"`
}

type CiaRequirementType string

const CiaRequirementTypeHIGH CiaRequirementType = "HIGH"
const CiaRequirementTypeLOW CiaRequirementType = "LOW"
const CiaRequirementTypeMEDIUM CiaRequirementType = "MEDIUM"
const CiaRequirementTypeNOTDEFINED CiaRequirementType = "NOT_DEFINED"

type CiaRequirementType_1 string

const CiaRequirementType_1_HIGH CiaRequirementType_1 = "HIGH"
const CiaRequirementType_1_LOW CiaRequirementType_1 = "LOW"
const CiaRequirementType_1_MEDIUM CiaRequirementType_1 = "MEDIUM"
const CiaRequirementType_1_NOTDEFINED CiaRequirementType_1 = "NOT_DEFINED"

type CiaType string

const CiaTypeCOMPLETE CiaType = "COMPLETE"
const CiaTypeNONE CiaType = "NONE"
const CiaTypePARTIAL CiaType = "PARTIAL"

type CiaType_1 string

const CiaType_1_HIGH CiaType_1 = "HIGH"
const CiaType_1_LOW CiaType_1 = "LOW"
const CiaType_1_NONE CiaType_1 = "NONE"

type CollateralDamagePotentialType string

const CollateralDamagePotentialTypeHIGH CollateralDamagePotentialType = "HIGH"
const CollateralDamagePotentialTypeLOW CollateralDamagePotentialType = "LOW"
const CollateralDamagePotentialTypeLOWMEDIUM CollateralDamagePotentialType = "LOW_MEDIUM"
const CollateralDamagePotentialTypeMEDIUMHIGH CollateralDamagePotentialType = "MEDIUM_HIGH"
const CollateralDamagePotentialTypeNONE CollateralDamagePotentialType = "NONE"
const CollateralDamagePotentialTypeNOTDEFINED CollateralDamagePotentialType = "NOT_DEFINED"

type ConfidenceType string

const ConfidenceTypeCONFIRMED ConfidenceType = "CONFIRMED"
const ConfidenceTypeNOTDEFINED ConfidenceType = "NOT_DEFINED"
const ConfidenceTypeREASONABLE ConfidenceType = "REASONABLE"
const ConfidenceTypeUNKNOWN ConfidenceType = "UNKNOWN"

type CriticalScoreType float64

type CriticalSeverityType string

type ExploitCodeMaturityType string

const ExploitCodeMaturityTypeFUNCTIONAL ExploitCodeMaturityType = "FUNCTIONAL"
const ExploitCodeMaturityTypeHIGH ExploitCodeMaturityType = "HIGH"
const ExploitCodeMaturityTypeNOTDEFINED ExploitCodeMaturityType = "NOT_DEFINED"
const ExploitCodeMaturityTypePROOFOFCONCEPT ExploitCodeMaturityType = "PROOF_OF_CONCEPT"
const ExploitCodeMaturityTypeUNPROVEN ExploitCodeMaturityType = "UNPROVEN"

type ExploitMaturityType string

const ExploitMaturityTypeATTACKED ExploitMaturityType = "ATTACKED"
const ExploitMaturityTypeNOTDEFINED ExploitMaturityType = "NOT_DEFINED"
const ExploitMaturityTypePROOFOFCONCEPT ExploitMaturityType = "PROOF_OF_CONCEPT"
const ExploitMaturityTypeUNREPORTED ExploitMaturityType = "UNREPORTED"

type ExploitabilityType string

const ExploitabilityTypeFUNCTIONAL ExploitabilityType = "FUNCTIONAL"
const ExploitabilityTypeHIGH ExploitabilityType = "HIGH"
const ExploitabilityTypeNOTDEFINED ExploitabilityType = "NOT_DEFINED"
const ExploitabilityTypePROOFOFCONCEPT ExploitabilityType = "PROOF_OF_CONCEPT"
const ExploitabilityTypeUNPROVEN ExploitabilityType = "UNPROVEN"

type HighScoreType float64

type HighSeverityType string

type LowScoreType float64

type LowSeverityType string

type MediumScoreType float64

type MediumSeverityType string

type ModifiedAttackComplexityType string

const ModifiedAttackComplexityTypeHIGH ModifiedAttackComplexityType = "HIGH"
const ModifiedAttackComplexityTypeLOW ModifiedAttackComplexityType = "LOW"
const ModifiedAttackComplexityTypeNOTDEFINED ModifiedAttackComplexityType = "NOT_DEFINED"

type ModifiedAttackComplexityType_1 string

const ModifiedAttackComplexityType_1_HIGH ModifiedAttackComplexityType_1 = "HIGH"
const ModifiedAttackComplexityType_1_LOW ModifiedAttackComplexityType_1 = "LOW"
const ModifiedAttackComplexityType_1_NOTDEFINED ModifiedAttackComplexityType_1 = "NOT_DEFINED"

type ModifiedAttackRequirementsType string

const ModifiedAttackRequirementsTypeNONE ModifiedAttackRequirementsType = "NONE"
const ModifiedAttackRequirementsTypeNOTDEFINED ModifiedAttackRequirementsType = "NOT_DEFINED"
const ModifiedAttackRequirementsTypePRESENT ModifiedAttackRequirementsType = "PRESENT"

type ModifiedAttackVectorType string

const ModifiedAttackVectorTypeADJACENT ModifiedAttackVectorType = "ADJACENT"
const ModifiedAttackVectorTypeLOCAL ModifiedAttackVectorType = "LOCAL"
const ModifiedAttackVectorTypeNETWORK ModifiedAttackVectorType = "NETWORK"
const ModifiedAttackVectorTypeNOTDEFINED ModifiedAttackVectorType = "NOT_DEFINED"
const ModifiedAttackVectorTypePHYSICAL ModifiedAttackVectorType = "PHYSICAL"

type ModifiedAttackVectorType_1 string

const ModifiedAttackVectorType_1_ADJACENTNETWORK ModifiedAttackVectorType_1 = "ADJACENT_NETWORK"
const ModifiedAttackVectorType_1_LOCAL ModifiedAttackVectorType_1 = "LOCAL"
const ModifiedAttackVectorType_1_NETWORK ModifiedAttackVectorType_1 = "NETWORK"
const ModifiedAttackVectorType_1_NOTDEFINED ModifiedAttackVectorType_1 = "NOT_DEFINED"
const ModifiedAttackVectorType_1_PHYSICAL ModifiedAttackVectorType_1 = "PHYSICAL"

type ModifiedCiaType string

const ModifiedCiaTypeHIGH ModifiedCiaType = "HIGH"
const ModifiedCiaTypeLOW ModifiedCiaType = "LOW"
const ModifiedCiaTypeNONE ModifiedCiaType = "NONE"
const ModifiedCiaTypeNOTDEFINED ModifiedCiaType = "NOT_DEFINED"

type ModifiedPrivilegesRequiredType string

const ModifiedPrivilegesRequiredTypeHIGH ModifiedPrivilegesRequiredType = "HIGH"
const ModifiedPrivilegesRequiredTypeLOW ModifiedPrivilegesRequiredType = "LOW"
const ModifiedPrivilegesRequiredTypeNONE ModifiedPrivilegesRequiredType = "NONE"
const ModifiedPrivilegesRequiredTypeNOTDEFINED ModifiedPrivilegesRequiredType = "NOT_DEFINED"

type ModifiedPrivilegesRequiredType_1 string

const ModifiedPrivilegesRequiredType_1_HIGH ModifiedPrivilegesRequiredType_1 = "HIGH"
const ModifiedPrivilegesRequiredType_1_LOW ModifiedPrivilegesRequiredType_1 = "LOW"
const ModifiedPrivilegesRequiredType_1_NONE ModifiedPrivilegesRequiredType_1 = "NONE"
const ModifiedPrivilegesRequiredType_1_NOTDEFINED ModifiedPrivilegesRequiredType_1 = "NOT_DEFINED"

type ModifiedScopeType string

const ModifiedScopeTypeCHANGED ModifiedScopeType = "CHANGED"
const ModifiedScopeTypeNOTDEFINED ModifiedScopeType = "NOT_DEFINED"
const ModifiedScopeTypeUNCHANGED ModifiedScopeType = "UNCHANGED"

type ModifiedSubCType string

const ModifiedSubCTypeHIGH ModifiedSubCType = "HIGH"
const ModifiedSubCTypeLOW ModifiedSubCType = "LOW"
const ModifiedSubCTypeNEGLIGIBLE ModifiedSubCType = "NEGLIGIBLE"
const ModifiedSubCTypeNOTDEFINED ModifiedSubCType = "NOT_DEFINED"

type ModifiedSubIaType string

const ModifiedSubIaTypeHIGH ModifiedSubIaType = "HIGH"
const ModifiedSubIaTypeLOW ModifiedSubIaType = "LOW"
const ModifiedSubIaTypeNEGLIGIBLE ModifiedSubIaType = "NEGLIGIBLE"
const ModifiedSubIaTypeNOTDEFINED ModifiedSubIaType = "NOT_DEFINED"
const ModifiedSubIaTypeSAFETY ModifiedSubIaType = "SAFETY"

type ModifiedUserInteractionType string

const ModifiedUserInteractionTypeACTIVE ModifiedUserInteractionType = "ACTIVE"
const ModifiedUserInteractionTypeNONE ModifiedUserInteractionType = "NONE"
const ModifiedUserInteractionTypeNOTDEFINED ModifiedUserInteractionType = "NOT_DEFINED"
const ModifiedUserInteractionTypePASSIVE ModifiedUserInteractionType = "PASSIVE"

type ModifiedUserInteractionType_1 string

const ModifiedUserInteractionType_1_NONE ModifiedUserInteractionType_1 = "NONE"
const ModifiedUserInteractionType_1_NOTDEFINED ModifiedUserInteractionType_1 = "NOT_DEFINED"
const ModifiedUserInteractionType_1_REQUIRED ModifiedUserInteractionType_1 = "REQUIRED"

type ModifiedVulnCiaType string

const ModifiedVulnCiaTypeHIGH ModifiedVulnCiaType = "HIGH"
const ModifiedVulnCiaTypeLOW ModifiedVulnCiaType = "LOW"
const ModifiedVulnCiaTypeNONE ModifiedVulnCiaType = "NONE"
const ModifiedVulnCiaTypeNOTDEFINED ModifiedVulnCiaType = "NOT_DEFINED"

type NoneScoreType float64

type NoneSeverityType string

type PrivilegesRequiredType string

const PrivilegesRequiredTypeHIGH PrivilegesRequiredType = "HIGH"
const PrivilegesRequiredTypeLOW PrivilegesRequiredType = "LOW"
const PrivilegesRequiredTypeNONE PrivilegesRequiredType = "NONE"

type ProviderUrgencyType string

const ProviderUrgencyTypeAMBER ProviderUrgencyType = "AMBER"
const ProviderUrgencyTypeCLEAR ProviderUrgencyType = "CLEAR"
const ProviderUrgencyTypeGREEN ProviderUrgencyType = "GREEN"
const ProviderUrgencyTypeNOTDEFINED ProviderUrgencyType = "NOT_DEFINED"
const ProviderUrgencyTypeRED ProviderUrgencyType = "RED"

type RecoveryType string

const RecoveryTypeAUTOMATIC RecoveryType = "AUTOMATIC"
const RecoveryTypeIRRECOVERABLE RecoveryType = "IRRECOVERABLE"
const RecoveryTypeNOTDEFINED RecoveryType = "NOT_DEFINED"
const RecoveryTypeUSER RecoveryType = "USER"

type RemediationLevelType string

const RemediationLevelTypeNOTDEFINED RemediationLevelType = "NOT_DEFINED"
const RemediationLevelTypeOFFICIALFIX RemediationLevelType = "OFFICIAL_FIX"
const RemediationLevelTypeTEMPORARYFIX RemediationLevelType = "TEMPORARY_FIX"
const RemediationLevelTypeUNAVAILABLE RemediationLevelType = "UNAVAILABLE"
const RemediationLevelTypeWORKAROUND RemediationLevelType = "WORKAROUND"

type ReportConfidenceType string

const ReportConfidenceTypeCONFIRMED ReportConfidenceType = "CONFIRMED"
const ReportConfidenceTypeNOTDEFINED ReportConfidenceType = "NOT_DEFINED"
const ReportConfidenceTypeUNCONFIRMED ReportConfidenceType = "UNCONFIRMED"
const ReportConfidenceTypeUNCORROBORATED ReportConfidenceType = "UNCORROBORATED"

type SafetyType string

const SafetyTypeNEGLIGIBLE SafetyType = "NEGLIGIBLE"
const SafetyTypeNOTDEFINED SafetyType = "NOT_DEFINED"
const SafetyTypePRESENT SafetyType = "PRESENT"

type ScopeType string

const ScopeTypeCHANGED ScopeType = "CHANGED"
const ScopeTypeUNCHANGED ScopeType = "UNCHANGED"

type ScoreType float64

type SeverityType string

const SeverityTypeCRITICAL SeverityType = "CRITICAL"
const SeverityTypeHIGH SeverityType = "HIGH"
const SeverityTypeLOW SeverityType = "LOW"
const SeverityTypeMEDIUM SeverityType = "MEDIUM"
const SeverityTypeNONE SeverityType = "NONE"

type SubCiaType string

const SubCiaTypeHIGH SubCiaType = "HIGH"
const SubCiaTypeLOW SubCiaType = "LOW"
const SubCiaTypeNONE SubCiaType = "NONE"

type TargetDistributionType string

const TargetDistributionTypeHIGH TargetDistributionType = "HIGH"
const TargetDistributionTypeLOW TargetDistributionType = "LOW"
const TargetDistributionTypeMEDIUM TargetDistributionType = "MEDIUM"
const TargetDistributionTypeNONE TargetDistributionType = "NONE"
const TargetDistributionTypeNOTDEFINED TargetDistributionType = "NOT_DEFINED"

type UserInteractionType string

const UserInteractionTypeACTIVE UserInteractionType = "ACTIVE"
const UserInteractionTypeNONE UserInteractionType = "NONE"
const UserInteractionTypePASSIVE UserInteractionType = "PASSIVE"

type UserInteractionType_1 string

const UserInteractionType_1_NONE UserInteractionType_1 = "NONE"
const UserInteractionType_1_REQUIRED UserInteractionType_1 = "REQUIRED"

type ValueDensityType string

const ValueDensityTypeCONCENTRATED ValueDensityType = "CONCENTRATED"
const ValueDensityTypeDIFFUSE ValueDensityType = "DIFFUSE"
const ValueDensityTypeNOTDEFINED ValueDensityType = "NOT_DEFINED"

type VulnCiaType string

const VulnCiaTypeHIGH VulnCiaType = "HIGH"
const VulnCiaTypeLOW VulnCiaType = "LOW"
const VulnCiaTypeNONE VulnCiaType = "NONE"

type VulnerabilityResponseEffortType string

const VulnerabilityResponseEffortTypeHIGH VulnerabilityResponseEffortType = "HIGH"
const VulnerabilityResponseEffortTypeLOW VulnerabilityResponseEffortType = "LOW"
const VulnerabilityResponseEffortTypeMODERATE VulnerabilityResponseEffortType = "MODERATE"
const VulnerabilityResponseEffortTypeNOTDEFINED VulnerabilityResponseEffortType = "NOT_DEFINED"
