// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// Representation of metadata for a CSAF Extension.
type ExtensionMetadataJson struct {
	// Contains the URL of the CSAF Extension Metadata JSON schema which the JSON
	// object promises to be valid for.
	Schema string `json:"$schema"`

	// Holds the `$id` value of the CSAF Extension Schema this metadata applies to.
	ExtensionSchema ContentSchemaT `json:"extension_schema"`

	// Contains a list of incompatible extensions.
	IncompatibleExtensions []ContentSchemaT `json:"incompatible_extensions,omitempty,omitzero"`

	// Holds the date and time when the document was last updated.
	LastUpdated DateTime `json:"last_updated"`

	// Contains the requirement for all possible paths.
	Requirement ExtensionMetadataJsonRequirement `json:"requirement"`
}

// Contains the requirement for all possible paths.
type ExtensionMetadataJsonRequirement struct {
	// Contains requirements for this extension on document path.
	DocumentXExtensions LocationT `json:"$.document.x_extensions"`

	// Contains requirements for this extension on the Product Tree Branch path.
	ProductTreeBranchesProductXExtensions LocationT `json:"$.product_tree.branches..product.x_extensions"`

	// Contains requirements for this extension on the Product Tree Full Product Names
	// path.
	ProductTreeFullProductNamesXExtensions LocationT `json:"$.product_tree.full_product_names[*].x_extensions"`

	// Contains requirements for this extension on the Product Tree Relationships
	// path.
	ProductTreeRelationshipsFullProductNameXExtensions LocationT `json:"$.product_tree.relationships[*].full_product_name.x_extensions"`

	// Contains requirements for this extension on the Vulnerabilities Metrics path.
	VulnerabilitiesMetricsContentXExtensions LocationT `json:"$.vulnerabilities[*].metrics[*].content.x_extensions"`

	// Contains requirements for this extension on the Vulnerabilities path.
	VulnerabilitiesXExtensions LocationT `json:"$.vulnerabilities[*].x_extensions"`

	// Contains requirements for this extension on the root path.
	XExtensions LocationT `json:"$.x_extensions"`
}

// Contains all necessary information for a single location.
type LocationT struct {
	// Contains the number how often the extension can be present in this path.
	MaxOccurrence int `json:"max_occurrence"`
}
