// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// Representation of additional information extending a CSAF Document.
type ExtensionContentJson struct {
	// Contains the URL of the CSAF Extension JSON schema which the JSON object
	// promises to be valid for.
	Schema ContentSchemaT `json:"$schema"`

	// Holds the category of the extension content.
	Category ExtensionContentJsonCategory `json:"category"`

	// Contains the additional information in its properties.
	Content ExtensionContentJsonContent `json:"content"`

	// Determines whether using the extension would fail a mandatory test.
	Critical bool `json:"critical"`
}

type ExtensionContentJsonCategory string

const ExtensionContentJsonCategoryEssential ExtensionContentJsonCategory = "essential"
const ExtensionContentJsonCategorySignificant ExtensionContentJsonCategory = "significant"
const ExtensionContentJsonCategorySupplementary ExtensionContentJsonCategory = "supplementary"

// Contains the additional information in its properties.
type ExtensionContentJsonContent map[string]interface{}
