// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// Contains the actual value of the $schema property.
type ContentSchemaT string

// Representation of a CSAF Extension Schema
type ExtensionMetaschemaJson struct {
	// Contains the definitions as object of the CSAF Extension Schema.
	Defs Schema `json:"$defs,omitempty,omitzero"`

	// Contains the ID as URL of the CSAF Extension JSON schema which identifies the
	// CSAF Extension Schema.
	ID ContentSchemaT `json:"$id"`

	// Contains the URL of the CSAF Extension Metaschema JSON schema which the JSON
	// schema promises to be valid for.
	Schema string `json:"$schema"`

	// Prohibits additional properties on this level.
	AdditionalProperties bool `json:"additionalProperties"`

	// Contains the description for the CSAF Extension Schema detailing what the CSAF
	// Extension is about.
	Description string `json:"description"`

	// Contains the definition of the properties a CSAF Extension Schema needs.
	Properties ExtensionMetaschemaJsonProperties `json:"properties"`

	// Contains the list of required properties.
	Required []interface{} `json:"required"`

	// Contains the title for the CSAF Extension Schema.
	Title string `json:"title"`

	// Contains the type of the CSAF Extension Schema which is always `object`.
	Type string `json:"type"`
}

// Contains the definition of the properties a CSAF Extension Schema needs.
type ExtensionMetaschemaJsonProperties struct {
	// Contains the definition of the object of the CSAF Extension JSON schema which
	// the JSON object promises to be valid for.
	Schema ExtensionMetaschemaJsonPropertiesSchema `json:"$schema"`

	// Contains the definition of the object of the CSAF Extension Category.
	Category ExtensionMetaschemaJsonPropertiesCategory `json:"category"`

	// Contains the definition of the object of the CSAF Extension content.
	Content Schema `json:"content"`

	// Contains the definition of the object of the CSAF Extension critical.
	Critical ExtensionMetaschemaJsonPropertiesCritical `json:"critical"`
}

// Contains the definition of the object of the CSAF Extension Category.
type ExtensionMetaschemaJsonPropertiesCategory struct {
	// Contains the description for the CSAF Extension category value.
	Description string `json:"description"`

	// Contains the possible options for the category.
	Enum []ExtensionMetaschemaJsonPropertiesCategoryEnumElem `json:"enum"`

	// Contains the title for the CSAF Extension category.
	Title string `json:"title"`

	// Contains the type of the category value which is `string`.
	Type string `json:"type"`
}

type ExtensionMetaschemaJsonPropertiesCategoryEnumElem string

const ExtensionMetaschemaJsonPropertiesCategoryEnumElemEssential ExtensionMetaschemaJsonPropertiesCategoryEnumElem = "essential"
const ExtensionMetaschemaJsonPropertiesCategoryEnumElemSignificant ExtensionMetaschemaJsonPropertiesCategoryEnumElem = "significant"
const ExtensionMetaschemaJsonPropertiesCategoryEnumElemSupplementary ExtensionMetaschemaJsonPropertiesCategoryEnumElem = "supplementary"

// Contains the definition of the object of the CSAF Extension critical.
type ExtensionMetaschemaJsonPropertiesCritical struct {
	// Contains the only allowed value of the critical value as defined by the CSAF
	// Extension Schema - either `true` or `false`.
	Const *ExtensionMetaschemaJsonPropertiesCriticalConst `json:"const,omitempty,omitzero"`

	// Contains the default of the critical value - either `true` or `false`.
	Default *ExtensionMetaschemaJsonPropertiesCriticalDefault `json:"default,omitempty,omitzero"`

	// Contains the description for the CSAF Extension critical value.
	Description string `json:"description"`

	// Contains the title for the CSAF Extension critical.
	Title string `json:"title"`

	// Contains the type of the critical value which is `boolean`.
	Type string `json:"type"`
}

type ExtensionMetaschemaJsonPropertiesCriticalConst bool

type ExtensionMetaschemaJsonPropertiesCriticalDefault string

const ExtensionMetaschemaJsonPropertiesCriticalDefaultFalse ExtensionMetaschemaJsonPropertiesCriticalDefault = "false"
const ExtensionMetaschemaJsonPropertiesCriticalDefaultTrue ExtensionMetaschemaJsonPropertiesCriticalDefault = "true"

// Contains the definition of the object of the CSAF Extension JSON schema which
// the JSON object promises to be valid for.
type ExtensionMetaschemaJsonPropertiesSchema struct {
	// Contains the actual value of the $schema property.
	Const *ContentSchemaT `json:"const,omitempty,omitzero"`

	// Contains the description for the CSAF Extension $schema value.
	Description string `json:"description"`

	// Contains the format of the $schema value which is `uri`.
	Format string `json:"format"`

	// Contains the pattern for value of the $schema property.
	Pattern *string `json:"pattern,omitempty,omitzero"`

	// Contains the title for the CSAF Extension $schema.
	Title string `json:"title"`

	// Contains the type of the $schema value which is `string`.
	Type string `json:"type"`
}

type Schema interface{}
