// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>
// Code generated by internal/generate/bundle_schema.py. DO NOT EDIT.

package v21

import "embed"

//go:embed schema/aggregator.json
//go:embed schema/csaf.json
//go:embed schema/extension-content.json
//go:embed schema/extension-metadata.json
//go:embed schema/extension-metaschema.json
//go:embed schema/external/certcc.github.io/SSVC/data/schema/v2/SelectionList_2_0_0.schema.json
//go:embed schema/external/www.first.org/cvss/cvss-v2.0.json
//go:embed schema/external/www.first.org/cvss/cvss-v3.0.json
//go:embed schema/external/www.first.org/cvss/cvss-v3.1.json
//go:embed schema/external/www.first.org/cvss/cvss-v4.0.json
//go:embed schema/external/www.first.org/cvss/meta.json
//go:embed schema/meta.json
//go:embed schema/provider.json
//go:embed schema/rolie-feed.json
var schemaFiles embed.FS

var schemaPaths = map[string]string{
	"https://certcc.github.io/SSVC/data/schema/v2/SelectionList_2_0_0.schema.json": "schema/external/certcc.github.io/SSVC/data/schema/v2/SelectionList_2_0_0.schema.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/aggregator.json":            "schema/aggregator.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/csaf.json":                  "schema/csaf.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-content.json":     "schema/extension-content.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metadata.json":    "schema/extension-metadata.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json":  "schema/extension-metaschema.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/meta.json":                  "schema/meta.json",
	"https://docs.oasis-open.org/csaf/csaf/v2.1/schema/provider.json":              "schema/provider.json",
	"https://www.first.org/cvss/cvss-v2.0.json":                                    "schema/external/www.first.org/cvss/cvss-v2.0.json",
	"https://www.first.org/cvss/cvss-v2.0.json?20170531":                           "schema/external/www.first.org/cvss/cvss-v2.0.json",
	"https://www.first.org/cvss/cvss-v3.0.json":                                    "schema/external/www.first.org/cvss/cvss-v3.0.json",
	"https://www.first.org/cvss/cvss-v3.0.json?20170531":                           "schema/external/www.first.org/cvss/cvss-v3.0.json",
	"https://www.first.org/cvss/cvss-v3.1.json":                                    "schema/external/www.first.org/cvss/cvss-v3.1.json",
	"https://www.first.org/cvss/cvss-v3.1.json?20211103":                           "schema/external/www.first.org/cvss/cvss-v3.1.json",
	"https://www.first.org/cvss/cvss-v4.0.json":                                    "schema/external/www.first.org/cvss/cvss-v4.0.json",
	"https://www.first.org/cvss/cvss-v4.0.json?20260226":                           "schema/external/www.first.org/cvss/cvss-v4.0.json",
	"https://www.first.org/cvss/meta.json":                                         "schema/external/www.first.org/cvss/meta.json",
	"urn:gocsaf:schema:csaf:2.1:rolie-feed":                                        "schema/rolie-feed.json",
}
