// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

package v21

// A minimal representation of a decision point value.
// Intended to parallel the DecisionPointValue object, but with fewer required
// fields.
// A decision point value is uniquely identified within a decision point by its
// key.
// Globally, the combination of Decision Point namespace, key, and version coupled
// with the value key
// uniquely identifies a value across all decision points and values.
// Other required fields in the DecisionPointValue object, such as name and
// description, are optional here.
type MinimalDecisionPointValue struct {
	// Definition corresponds to the JSON schema field "definition".
	Definition *string `json:"definition,omitempty,omitzero"`

	// A short, non-empty string identifier for the object. Keys must start with an
	// alphanumeric, contain only alphanumerics and `_`, and end with an
	// alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should
	// not be used for new objects.)
	Key string `json:"key"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`
}

// A reference to a resource that provides additional context about the decision
// points or selections.
// This object is intentionally minimal and contains only the URL and an optional
// description.
type Reference struct {
	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`

	// URI corresponds to the JSON schema field "uri".
	URI string `json:"uri"`
}

// This schema defines the structure to represent an SSVC SelectionList object.
type SSVCV2 struct {
	// A list of resources that provide additional context about the decision points
	// found in this selection.
	DecisionPointResources []Reference `json:"decision_point_resources,omitempty,omitzero"`

	// A list of references that provide additional context about the specific values
	// selected.
	References []Reference `json:"references,omitempty,omitzero"`

	// The schema version of this selection list.
	SchemaVersion SSVCV2SchemaVersion `json:"schemaVersion"`

	// List of selections made from decision points. Each selection item corresponds
	// to value keys contained in a specific decision point identified by its
	// namespace, key, and version. Note that selection objects are deliberately
	// minimal objects and do not contain the full decision point details.
	Selections []Selection `json:"selections"`

	// Optional list of identifiers for the item or items (vulnerabilities, reports,
	// advisories, systems, assets, etc.) being evaluated by these selections.
	TargetIds []string `json:"target_ids,omitempty,omitzero"`

	// Timestamp of the selections, in RFC 3339 format.
	Timestamp DateTime `json:"timestamp"`
}

// A minimal selection object that contains the decision point ID and the selected
// values.
// While the Selection object parallels the DecisionPoint object, it is
// intentionally minimal, with
// fewer required fields and no additional metadata, as it is meant to represent a
// selection made from a
// previously defined decision point. The expectation is that a Selection object
// will usually have
// fewer values than the original decision point, as it represents a specific
// evaluation
// at a specific time and may therefore rule out some values that were previously
// considered.
// Other fields like name and description may be copied from the decision point,
// but are not required.
type Selection struct {
	// Definition corresponds to the JSON schema field "definition".
	Definition *string `json:"definition,omitempty,omitzero"`

	// A short, non-empty string identifier for the object. Keys must start with an
	// alphanumeric, contain only alphanumerics and `_`, and end with an
	// alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should
	// not be used for new objects.)
	Key string `json:"key"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero"`

	// The namespace of the SSVC object.
	Namespace string `json:"namespace"`

	// A list of selected value keys from the decision point values.
	Values []MinimalDecisionPointValue `json:"values"`

	// The version of the SSVC object. This must be a valid semantic version string.
	Version string `json:"version"`
}
