// Code generated by schemagen. DO NOT EDIT.
//   timestamp: 2026-09-07T08:02:15Z

package comparison

import (
	_ "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"time"
)







// FileHashesItem Contains one hash value and algorithm of the file to be identified.
type FileHashesItem struct {
	// Contains the name of the cryptographic hash algorithm used to calculate the value.
	Algorithm string `json:"algorithm" validate:"required,min=1"`
	// Contains the cryptographic hash value in lowercase hexadecimal representation.
	Value string `json:"value" validate:"required,min=32"`
}

// HashesItem Contains all information to identify a file based on its cryptographic hash values.
type HashesItem struct {
	// Contains a list of cryptographic hashes for this file.
	FileHashes []FileHashesItem `json:"file_hashes" validate:"required,min=1"`
	// Contains the name of the file which is identified by the hash values.
	Filename string `json:"filename" validate:"required,min=1"`
}

// XGenericUrisItem Provides a generic extension point for any identifier which is either vendor-specific or derived from a standard not yet supported.
type XGenericUrisItem struct {
	// Refers to a URL which provides the name and knowledge about the specification used or is the namespace in which these values are valid.
	Namespace string `json:"namespace" validate:"required,url"`
	// Contains the identifier itself.
	Uri string `json:"uri" validate:"required,url"`
}

// ProductIdentificationHelper Provides at least one method which aids in identifying the product in an asset database.
type ProductIdentificationHelper struct {
	// The Common Platform Enumeration (CPE) attribute refers to a method for naming platforms external to this specification.
	Cpe *string `json:"cpe,omitempty" validate:"min=5"`
	// Contains a list of cryptographic hashes usable to identify files.
	Hashes *[]HashesItem `json:"hashes,omitempty" validate:"min=1"`
	// Contains a list of model numbers.
	ModelNumbers *[]string `json:"model_numbers,omitempty" validate:"min=1"`
	// Contains a list of Package-URLs (PURL).
	Purls *[]string `json:"purls,omitempty" validate:"min=1"`
	// Contains a list of URLs where SBOMs for this product can be retrieved.
	SbomUrls *[]string `json:"sbom_urls,omitempty" validate:"min=1"`
	// Contains a list of serial numbers.
	SerialNumbers *[]string `json:"serial_numbers,omitempty" validate:"min=1"`
	// Contains a list of stock keeping units.
	Skus *[]string `json:"skus,omitempty" validate:"min=1"`
	// Contains a list of identifiers which are either vendor-specific or derived from a standard not yet supported.
	XGenericUris *[]XGenericUrisItem `json:"x_generic_uris,omitempty" validate:"min=1"`
}

// FullProductNameT Specifies information about the product and assigns the product_id.
type FullProductNameT struct {
	// The value should be the product’s full canonical name, including version number and other attributes, as it would be used in a human-friendly document.
	Name string `json:"name" validate:"required,min=1"`
	ProductId ProductIdT `json:"product_id" validate:"required"`
	// Provides at least one method which aids in identifying the product in an asset database.
	ProductIdentificationHelper *ProductIdentificationHelper `json:"product_identification_helper,omitempty"`
	// Contains a list of extensions valid at the full product name element level of the CSAF document and associated with this full product name element.
	XExtensions *ExtensionsT `json:"x_extensions,omitempty"`
}















// Category Defines the category of relationship between the previous item and the referenced next product.
type Category string

const (
	CategoryDEFAULT_COMPONENT_OF Category = "default_component_of"
	CategoryEXTERNAL_COMPONENT_OF Category = "external_component_of"
	CategoryINSTALLED_ON Category = "installed_on"
	CategoryINSTALLED_WITH Category = "installed_with"
	CategoryOPTIONAL_COMPONENT_OF Category = "optional_component_of"
)

// SubpathT Contains the next node along the current path and its relationship to the previous node.
type SubpathT struct {
	// Defines the category of relationship between the previous item and the referenced next product.
	Category Category `json:"category" validate:"required"`
	// Holds a Product ID that refers to the Full Product Name element, which is referenced as the second element of the relationship.
	NextProductReference ProductIdT `json:"next_product_reference" validate:"required"`
}



// $schema Contains the URL of the CSAF JSON schema which the document promises to be valid for.
type $schema string

const (
	$schemaHTTPS://DOCS_OASIS_OPEN_ORG/CSAF/CSAF/V2_1/SCHEMA/CSAF_JSON $schema = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/csaf.json"
)

// AggregateSeverity Is a vehicle that is provided by the document producer to convey the urgency and criticality with which the one or more vulnerabilities reported should be addressed. It is a document-level metric and applied to the document as a whole — not any specific vulnerability. The range of values in this field is defined according to the document producer's policies and procedures.
type AggregateSeverity struct {
	// Points to the namespace so referenced.
	Namespace *string `json:"namespace,omitempty" validate:"url"`
	// Provides a severity which is independent of - and in addition to - any other standard metric for determining the impact or severity of a given vulnerability (such as CVSS).
	Text string `json:"text" validate:"required,min=1"`
}

// CsafVersion Gives the version of the CSAF specification which the document was generated for.
type CsafVersion string

const (
	CsafVersion2_1 CsafVersion = "2.1"
)

// SharingGroup Contains information about the group this document is intended to be shared with.
type SharingGroup struct {
	// Provides the unique ID for the sharing group.
	Id uuid.UUID `json:"id" validate:"required,uuid"`
	// Contains a human-readable name for the sharing group.
	Name *string `json:"name,omitempty" validate:"min=1"`
}

// Label Provides the TLP label of the document.
type Label string

const (
	LabelAMBER Label = "AMBER"
	LabelAMBER+STRICT Label = "AMBER+STRICT"
	LabelCLEAR Label = "CLEAR"
	LabelGREEN Label = "GREEN"
	LabelRED Label = "RED"
)

// Tlp Provides details about the TLP classification of the document.
type Tlp struct {
	// Provides the TLP label of the document.
	Label Label `json:"label" validate:"required"`
	// Provides a URL where to find the textual description of the TLP version which is used in this document. Default is the URL to the definition by FIRST.
	Url *string `json:"url,omitempty" validate:"url"`
}

// Distribution Describe any constraints on how this document might be shared.
type Distribution struct {
	// Contains information about the group this document is intended to be shared with.
	SharingGroup *SharingGroup `json:"sharing_group,omitempty"`
	// Provides a textual description of additional constraints.
	Text *string `json:"text,omitempty" validate:"min=1"`
	// Provides details about the TLP classification of the document.
	Tlp Tlp `json:"tlp" validate:"required"`
}

// Category2 Provides information about the category of publisher releasing the document.
type Category2 string

const (
	Category2COORDINATOR Category2 = "coordinator"
	Category2DISCOVERER Category2 = "discoverer"
	Category2MULTIPLIER Category2 = "multiplier"
	Category2OTHER Category2 = "other"
	Category2TRANSLATOR Category2 = "translator"
	Category2USER Category2 = "user"
	Category2VENDOR Category2 = "vendor"
)

// Contact Contains information on how to contact the publisher.
type Contact struct {
	// Contains details regarding ways to reach the publisher, e.g. through web sites, phone numbers, and postal mail addresses.
	Details *string `json:"details,omitempty" validate:"min=1"`
	// Contains the email address that can be used to reach the issuing party.
	Email *string `json:"email,omitempty" validate:"min=6,email"`
	// Contains a URL pointing to a public OpenPGP key valid for the email of issuing party provided in the sibling property `email`.
	PublicOpenpgpKeyUrl *string `json:"public_openpgp_key_url,omitempty" validate:"min=11,url"`
}

// Publisher Provides information about the publisher of the document.
type Publisher struct {
	// Provides information about the category of publisher releasing the document.
	Category Category2 `json:"category" validate:"required"`
	// Contains information on how to contact the publisher.
	Contact *Contact `json:"contact,omitempty"`
	// Provides information about the authority of the issuing party to release the document, in particular, the party's constituency and responsibilities or other obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty" validate:"min=1"`
	// Contains the name of the issuing party.
	Name string `json:"name" validate:"required,min=1"`
	// Contains a URL which is under control of the issuing party and can be used as a globally unique identifier for that issuing party.
	Namespace string `json:"namespace" validate:"required,url"`
}

// Engine Contains information about the engine that generated the CSAF document.
type Engine struct {
	// Represents the name of the engine that generated the CSAF document.
	Name string `json:"name" validate:"required,min=1"`
	// Contains the version of the engine that generated the CSAF document.
	Version *string `json:"version,omitempty" validate:"min=1"`
}

// Generator Is a container to hold all elements related to the generation of the document. These items will reference when the document was actually created, including the date it was generated and the entity that generated it.
type Generator struct {
	// This SHOULD be the current date that the document was generated. Because documents are often generated internally by a document producer and exist for a nonzero amount of time before being released, this field MAY be different from the Initial Release Date and Current Release Date.
	Date *time.Time `json:"date,omitempty"`
	// Contains information about the engine that generated the CSAF document.
	Engine Engine `json:"engine" validate:"required"`
}

// RevisionHistoryItem Contains all the information elements required to track the evolution of a CSAF document.
type RevisionHistoryItem struct {
	// The date of the revision entry
	Date time.Time `json:"date" validate:"required"`
	// Contains the version string used in an existing document with the same content.
	LegacyVersion *string `json:"legacy_version,omitempty" validate:"min=1"`
	Number VersionT `json:"number" validate:"required"`
	// Holds a single non-empty string representing a short description of the changes.
	Summary string `json:"summary" validate:"required,min=1"`
}

// Status Defines the draft status of the document.
type Status string

const (
	StatusDRAFT Status = "draft"
	StatusFINAL Status = "final"
	StatusINTERIM Status = "interim"
)

// Tracking Is a container designated to hold all management attributes necessary to track a CSAF document as a whole.
type Tracking struct {
	// Contains a list of alternate names for the same document.
	Aliases *[]string `json:"aliases,omitempty" validate:"min=1"`
	// The date when the current revision of this document was released
	CurrentReleaseDate time.Time `json:"current_release_date" validate:"required"`
	// Is a container to hold all elements related to the generation of the document. These items will reference when the document was actually created, including the date it was generated and the entity that generated it.
	Generator *Generator `json:"generator,omitempty"`
	// The ID is a simple label that provides for a wide range of numbering values, types, and schemes. Its value SHOULD be assigned and maintained by the original document issuing authority.
	Id string `json:"id" validate:"required,min=1"`
	// The date when this document was first released to the specified target group.
	InitialReleaseDate time.Time `json:"initial_release_date" validate:"required"`
	// Holds one revision item for each version of the CSAF document, including the initial one.
	RevisionHistory []RevisionHistoryItem `json:"revision_history" validate:"required,min=1"`
	// Defines the draft status of the document.
	Status Status `json:"status" validate:"required"`
	Version VersionT `json:"version" validate:"required"`
}

// Document Captures the meta-data about this document describing a particular set of security advisories.
type Document struct {
	// Contains a list of acknowledgment elements associated with the whole document.
	Acknowledgments *AcknowledgmentsT `json:"acknowledgments,omitempty"`
	// Is a vehicle that is provided by the document producer to convey the urgency and criticality with which the one or more vulnerabilities reported should be addressed. It is a document-level metric and applied to the document as a whole — not any specific vulnerability. The range of values in this field is defined according to the document producer's policies and procedures.
	AggregateSeverity *AggregateSeverity `json:"aggregate_severity,omitempty"`
	// Defines a short canonical name, chosen by the document producer, which will inform the end user as to the category of document.
	Category string `json:"category" validate:"required,min=1"`
	// Gives the version of the CSAF specification which the document was generated for.
	CsafVersion CsafVersion `json:"csaf_version" validate:"required"`
	// Describe any constraints on how this document might be shared.
	Distribution Distribution `json:"distribution" validate:"required"`
	// Identifies the language used by this document, corresponding to IETF BCP 47 / RFC 5646.
	Lang *LangT `json:"lang,omitempty"`
	// Contains the SPDX license expression for the CSAF document.
	LicenseExpression *string `json:"license_expression,omitempty" validate:"min=1"`
	// Holds notes associated with the whole document.
	Notes *NotesT `json:"notes,omitempty"`
	// Provides information about the publisher of the document.
	Publisher Publisher `json:"publisher" validate:"required"`
	// Holds a list of references associated with the whole document.
	References *ReferencesT `json:"references,omitempty"`
	// If this copy of the document is a translation then the value of this property describes from which language this document was translated.
	SourceLang *LangT `json:"source_lang,omitempty"`
	// This SHOULD be a canonical name for the document, and sufficiently unique to distinguish it from similar documents.
	Title string `json:"title" validate:"required,min=1"`
	// Is a container designated to hold all management attributes necessary to track a CSAF document as a whole.
	Tracking Tracking `json:"tracking" validate:"required"`
	// Contains a list of extensions valid at the document property level of the CSAF document and associated with this document metadata.
	XExtensions *ExtensionsT `json:"x_extensions,omitempty"`
}

// ProductGroupsItem Defines a new logical group of products that can then be referred to in other parts of the document to address a group of products with a single identifier.
type ProductGroupsItem struct {
	GroupId ProductGroupIdT `json:"group_id" validate:"required"`
	// Lists the product_ids of those products which known as one group in the document.
	ProductIds []ProductIdT `json:"product_ids" validate:"required,min=2"`
	// Gives a short, optional description of the group.
	Summary *string `json:"summary,omitempty" validate:"min=1"`
}

// ProductPathsItem Establishes a path along existing full_product_name_t elements, allowing the document producer to define a path of multiple products that form a new full_product_name entry.
type ProductPathsItem struct {
	// Holds a Product ID that refers to the Full Product Name element, which is the beginning node of the product path.
	BeginningProductReference ProductIdT `json:"beginning_product_reference" validate:"required"`
	FullProductName FullProductNameT `json:"full_product_name" validate:"required"`
	// Contains an ordered list of product subpaths, each one relating to the path defined by all previous elements up to the beginning node of the product path.
	Subpaths []SubpathT `json:"subpaths" validate:"required,min=1"`
}

// ProductTree Is a container for all fully qualified product names that can be referenced elsewhere in the document.
type ProductTree struct {
	Branches *BranchesT `json:"branches,omitempty"`
	// Contains a list of full product names.
	FullProductNames *[]FullProductNameT `json:"full_product_names,omitempty" validate:"min=1"`
	// Contains a list of product groups.
	ProductGroups *[]ProductGroupsItem `json:"product_groups,omitempty" validate:"min=1"`
	// Contains a list of product paths.
	ProductPaths *[]ProductPathsItem `json:"product_paths,omitempty" validate:"min=1"`
}

// CwesItem Holds the MITRE standard Common Weakness Enumeration (CWE) for the weakness associated.
type CwesItem struct {
	// Holds the ID for the weakness associated.
	Id string `json:"id" validate:"required"`
	// Holds the full name of the weakness as given in the CWE specification.
	Name string `json:"name" validate:"required,min=1"`
	// Holds the version string of the CWE specification this weakness was extracted from.
	Version string `json:"version" validate:"required"`
}

// FirstKnownExploitationDatesItem Contains information on when this vulnerability was first known to be exploited in the wild in the products specified.
type FirstKnownExploitationDatesItem struct {
	// Contains the date when the information was last updated.
	Date time.Time `json:"date" validate:"required"`
	// Contains the date when the exploitation happened.
	ExploitationDate time.Time `json:"exploitation_date" validate:"required"`
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
}

// Label2 Specifies the machine readable label.
type Label2 string

const (
	Label2COMPONENT_NOT_PRESENT Label2 = "component_not_present"
	Label2INLINE_MITIGATIONS_ALREADY_EXIST Label2 = "inline_mitigations_already_exist"
	Label2VULNERABLE_CODE_CANNOT_BE_CONTROLLED_BY_ADVERSARY Label2 = "vulnerable_code_cannot_be_controlled_by_adversary"
	Label2VULNERABLE_CODE_NOT_IN_EXECUTE_PATH Label2 = "vulnerable_code_not_in_execute_path"
	Label2VULNERABLE_CODE_NOT_PRESENT Label2 = "vulnerable_code_not_present"
)

// FlagsItem Contains product specific information in regard to this vulnerability as a single machine readable flag.
type FlagsItem struct {
	// Contains the date when assessment was done or the flag was assigned.
	Date *time.Time `json:"date,omitempty"`
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	// Specifies the machine readable label.
	Label Label2 `json:"label" validate:"required"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
}

// IdsItem Contains a single unique label or tracking ID for the vulnerability.
type IdsItem struct {
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
	// Indicates the name of the vulnerability tracking or numbering system.
	SystemName string `json:"system_name" validate:"required,min=1"`
	// Is unique label or tracking ID for the vulnerability (if such information exists).
	Text string `json:"text" validate:"required,min=1"`
}

// Party Defines the category of the involved party.
type Party string

const (
	PartyCOORDINATOR Party = "coordinator"
	PartyDISCOVERER Party = "discoverer"
	PartyOTHER Party = "other"
	PartyUSER Party = "user"
	PartyVENDOR Party = "vendor"
)

// Status2 Defines contact status of the involved party.
type Status2 string

const (
	Status2COMPLETED Status2 = "completed"
	Status2CONTACT_ATTEMPTED Status2 = "contact_attempted"
	Status2DISPUTED Status2 = "disputed"
	Status2IN_PROGRESS Status2 = "in_progress"
	Status2NOT_CONTACTED Status2 = "not_contacted"
	Status2OPEN Status2 = "open"
)

// InvolvementsItem Is a container, that allows the document producers to comment on the level of involvement (or engagement) of themselves or third parties in the vulnerability identification, scoping, and remediation process.
type InvolvementsItem struct {
	// Contains the contact information of the party that was used in this state.
	Contact *string `json:"contact,omitempty" validate:"min=1"`
	// Holds the date and time of the involvement entry.
	Date *time.Time `json:"date,omitempty"`
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	// Defines the category of the involved party.
	Party Party `json:"party" validate:"required"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
	// Defines contact status of the involved party.
	Status Status2 `json:"status" validate:"required"`
	// Contains additional context regarding what is going on.
	Summary *string `json:"summary,omitempty" validate:"min=1"`
}

// Epss Contains the EPSS data.
type Epss struct {
	// Contains the rank ordering of probabilities from highest to lowest.
	Percentile string `json:"percentile" validate:"required"`
	// Contains the likelihood that any exploitation activity for this Vulnerability is being observed in the 30 days following the given timestamp.
	Probability string `json:"probability" validate:"required"`
	// Holds the date and time the EPSS value was recorded.
	Timestamp time.Time `json:"timestamp" validate:"required"`
}

// QualitativeSeverityRating Contains an assessment of the severity of the vulnerability regarding the products on a qualitative scale.
type QualitativeSeverityRating string

const (
	QualitativeSeverityRatingCRITICAL QualitativeSeverityRating = "critical"
	QualitativeSeverityRatingHIGH QualitativeSeverityRating = "high"
	QualitativeSeverityRatingLOW QualitativeSeverityRating = "low"
	QualitativeSeverityRatingMEDIUM QualitativeSeverityRating = "medium"
	QualitativeSeverityRatingNONE QualitativeSeverityRating = "none"
)

// Content Specifies information about (at least one) metric or score for the given products regarding the current vulnerability.
type Content struct {
	CvssV2 *CvssV20 `json:"cvss_v2,omitempty"`
	// Can be one of: CvssV30, CvssV31
	CvssV3 *any `json:"cvss_v3,omitempty"`
	CvssV4 *CvssV40 `json:"cvss_v4,omitempty"`
	// Contains the EPSS data.
	Epss *Epss `json:"epss,omitempty"`
	// Contains an assessment of the severity of the vulnerability regarding the products on a qualitative scale.
	QualitativeSeverityRating *QualitativeSeverityRating `json:"qualitative_severity_rating,omitempty"`
	SsvcV2 *SelectionList200Schema `json:"ssvc_v2,omitempty"`
	// Contains a list of extensions valid at the metrics-content-level of the CSAF document and associated with this metric element.
	XExtensions *ExtensionsT `json:"x_extensions,omitempty"`
}

// MetricsItem Contains all metadata about the metric including products it applies to and the source and the content itself.
type MetricsItem struct {
	// Specifies information about (at least one) metric or score for the given products regarding the current vulnerability.
	Content Content `json:"content" validate:"required"`
	Products ProductsT `json:"products" validate:"required"`
	// Contains the URL of the source that originally determined the metric.
	Source *string `json:"source,omitempty" validate:"url"`
}

// ProductStatus Contains different lists of product_ids which provide details on the status of the referenced product related to the current vulnerability. 
type ProductStatus struct {
	// These are the first versions of the releases known to be affected by the vulnerability.
	FirstAffected *ProductsT `json:"first_affected,omitempty"`
	// These versions contain the first fix for the vulnerability but may not be the recommended fixed versions.
	FirstFixed *ProductsT `json:"first_fixed,omitempty"`
	// These versions contain a fix for the vulnerability but may not be the recommended fixed versions.
	Fixed *ProductsT `json:"fixed,omitempty"`
	// These versions are known to be affected by the vulnerability.
	KnownAffected *ProductsT `json:"known_affected,omitempty"`
	// These versions are known not to be affected by the vulnerability.
	KnownNotAffected *ProductsT `json:"known_not_affected,omitempty"`
	// These are the last versions in a release train known to be affected by the vulnerability. Subsequently released versions would contain a fix for the vulnerability.
	LastAffected *ProductsT `json:"last_affected,omitempty"`
	// These versions have a fix for the vulnerability and are the vendor-recommended versions for fixing the vulnerability.
	Recommended *ProductsT `json:"recommended,omitempty"`
	// It is not known yet whether these versions are or are not affected by the vulnerability. However, it is still under investigation - the result will be provided in a later release of the document.
	UnderInvestigation *ProductsT `json:"under_investigation,omitempty"`
	// It is not known whether these versions are or are not affected by the vulnerability. There is also no investigation and therefore the status might never be determined.
	Unknown *ProductsT `json:"unknown,omitempty"`
}

// Category3 Specifies the category which this remediation belongs to.
type Category3 string

const (
	Category3FIX_PLANNED Category3 = "fix_planned"
	Category3MITIGATION Category3 = "mitigation"
	Category3NO_FIX_PLANNED Category3 = "no_fix_planned"
	Category3NONE_AVAILABLE Category3 = "none_available"
	Category3OPTIONAL_PATCH Category3 = "optional_patch"
	Category3VENDOR_FIX Category3 = "vendor_fix"
	Category3WORKAROUND Category3 = "workaround"
)

// Category4 Specifies what category of restart is required by this remediation to become effective.
type Category4 string

const (
	Category4CONNECTED Category4 = "connected"
	Category4DEPENDENCIES Category4 = "dependencies"
	Category4MACHINE Category4 = "machine"
	Category4NONE Category4 = "none"
	Category4PARENT Category4 = "parent"
	Category4SERVICE Category4 = "service"
	Category4SYSTEM Category4 = "system"
	Category4VULNERABLE_COMPONENT Category4 = "vulnerable_component"
	Category4ZONE Category4 = "zone"
)

// RestartRequired Provides information on the category of restart required by this remediation to become effective.
type RestartRequired struct {
	// Specifies what category of restart is required by this remediation to become effective.
	Category Category4 `json:"category" validate:"required"`
	// Provides additional information for the restart. This can include details on procedures, scope or impact.
	Details *string `json:"details,omitempty" validate:"min=1"`
}

// RemediationsItem Specifies details on how to handle (and presumably, fix) a vulnerability.
type RemediationsItem struct {
	// Specifies the category which this remediation belongs to.
	Category Category3 `json:"category" validate:"required"`
	// Contains the date from which the remediation is available.
	Date *time.Time `json:"date,omitempty"`
	// Contains a thorough human-readable discussion of the remediation.
	Details string `json:"details" validate:"required,min=1"`
	// Contains a list of entitlements.
	Entitlements *[]string `json:"entitlements,omitempty" validate:"min=1"`
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
	// Provides information on the category of restart required by this remediation to become effective.
	RestartRequired *RestartRequired `json:"restart_required,omitempty"`
	// Contains the URL where to obtain the remediation.
	Url *string `json:"url,omitempty" validate:"url"`
}

// Category5 Categorizes the threat according to the rules of the specification.
type Category5 string

const (
	Category5EXPLOIT_STATUS Category5 = "exploit_status"
	Category5IMPACT Category5 = "impact"
	Category5TARGET_SET Category5 = "target_set"
)

// ThreatsItem Contains the vulnerability kinetic information. This information can change as the vulnerability ages and new information becomes available.
type ThreatsItem struct {
	// Categorizes the threat according to the rules of the specification.
	Category Category5 `json:"category" validate:"required"`
	// Contains the date when the assessment was done or the threat appeared.
	Date *time.Time `json:"date,omitempty"`
	// Represents a thorough human-readable discussion of the threat.
	Details string `json:"details" validate:"required,min=1"`
	GroupIds *ProductGroupsT `json:"group_ids,omitempty"`
	ProductIds *ProductsT `json:"product_ids,omitempty"`
}

// VulnerabilitiesItem Is a container for the aggregation of all fields that are related to a single vulnerability in the document.
type VulnerabilitiesItem struct {
	// Contains a list of acknowledgment elements associated with this vulnerability item.
	Acknowledgments *AcknowledgmentsT `json:"acknowledgments,omitempty"`
	// Holds the MITRE standard Common Vulnerabilities and Exposures (CVE) tracking number for the vulnerability.
	Cve *string `json:"cve,omitempty"`
	// Contains a list of CWEs.
	Cwes *[]CwesItem `json:"cwes,omitempty" validate:"min=1"`
	// Holds the date and time the vulnerability was originally disclosed to the public.
	DisclosureDate *time.Time `json:"disclosure_date,omitempty"`
	// Holds the date and time the vulnerability was originally discovered.
	DiscoveryDate *time.Time `json:"discovery_date,omitempty"`
	// Contains a list of dates of first known exploitations.
	FirstKnownExploitationDates *[]FirstKnownExploitationDatesItem `json:"first_known_exploitation_dates,omitempty" validate:"min=1"`
	// Contains a list of machine readable flags.
	Flags *[]FlagsItem `json:"flags,omitempty" validate:"min=1"`
	// Represents a list of unique labels or tracking IDs for the vulnerability (if such information exists).
	Ids *[]IdsItem `json:"ids,omitempty" validate:"min=1"`
	// Contains a list of involvements.
	Involvements *[]InvolvementsItem `json:"involvements,omitempty" validate:"min=1"`
	// Contains metric objects for the current vulnerability.
	Metrics *[]MetricsItem `json:"metrics,omitempty" validate:"min=1"`
	// Holds notes associated with this vulnerability item.
	Notes *NotesT `json:"notes,omitempty"`
	// Contains different lists of product_ids which provide details on the status of the referenced product related to the current vulnerability. 
	ProductStatus *ProductStatus `json:"product_status,omitempty"`
	// Holds a list of references associated with this vulnerability item.
	References *ReferencesT `json:"references,omitempty"`
	// Contains a list of remediations.
	Remediations *[]RemediationsItem `json:"remediations,omitempty" validate:"min=1"`
	// Contains information about a vulnerability that can change with time.
	Threats *[]ThreatsItem `json:"threats,omitempty" validate:"min=1"`
	// Gives the document producer the ability to apply a canonical name or title to the vulnerability.
	Title *string `json:"title,omitempty" validate:"min=1"`
	// Contains a list of extensions valid at the vulnerability item level of the CSAF document and associated with this vulnerability element.
	XExtensions *ExtensionsT `json:"x_extensions,omitempty"`
}

// CommonSecurityAdvisoryFramework Representation of security advisory information as a JSON document.
type CommonSecurityAdvisoryFramework struct {
	// Contains the URL of the CSAF JSON schema which the document promises to be valid for.
	FSchema $schema `json:"$schema" validate:"required"`
	// Captures the meta-data about this document describing a particular set of security advisories.
	Document Document `json:"document" validate:"required"`
	// Is a container for all fully qualified product names that can be referenced elsewhere in the document.
	ProductTree *ProductTree `json:"product_tree,omitempty"`
	// Represents a list of all relevant vulnerability information items.
	Vulnerabilities *[]VulnerabilitiesItem `json:"vulnerabilities,omitempty" validate:"min=1"`
	// Contains a list of extensions valid at the root-level of the CSAF document and associated with this CSAF document.
	XExtensions *ExtensionsT `json:"x_extensions,omitempty"`
}