// SPDX-License-Identifier: Apache-2.0

// Code generated by go-jsonschema and internal/generate/prepare_v20_model.py. DO NOT EDIT.

package v20

// Contains a list of acknowledgment elements.
type AcknowledgmentsT []struct {
	// Contains the names of entities being recognized.
	Names []string `json:"names,omitempty,omitzero"`

	// Contains the name of a contributing organization being recognized.
	Organization *string `json:"organization,omitempty,omitzero"`

	// SHOULD represent any contextual details the document producers wish to make
	// known about the acknowledgment or acknowledged parties.
	Summary *string `json:"summary,omitempty,omitzero"`

	// Specifies a list of URLs or location of the reference to be acknowledged.
	Urls []string `json:"urls,omitempty,omitzero"`
}

// Contains branch elements as children of the current element.
type BranchesT []struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches *BranchesT `json:"branches,omitempty,omitzero"`

	// Describes the characteristics of the labeled branch.
	Category BranchesTElemCategory `json:"category"`

	// Contains the canonical descriptor or 'friendly name' of the branch.
	Name string `json:"name"`

	// Product corresponds to the JSON schema field "product".
	Product *FullProductNameT `json:"product,omitempty,omitzero"`
}

type BranchesTElemCategory string

const BranchesTElemCategoryArchitecture BranchesTElemCategory = "architecture"
const BranchesTElemCategoryHostName BranchesTElemCategory = "host_name"
const BranchesTElemCategoryLanguage BranchesTElemCategory = "language"
const BranchesTElemCategoryLegacy BranchesTElemCategory = "legacy"
const BranchesTElemCategoryPatchLevel BranchesTElemCategory = "patch_level"
const BranchesTElemCategoryProductFamily BranchesTElemCategory = "product_family"
const BranchesTElemCategoryProductName BranchesTElemCategory = "product_name"
const BranchesTElemCategoryProductVersion BranchesTElemCategory = "product_version"
const BranchesTElemCategoryProductVersionRange BranchesTElemCategory = "product_version_range"
const BranchesTElemCategoryServicePack BranchesTElemCategory = "service_pack"
const BranchesTElemCategorySpecification BranchesTElemCategory = "specification"
const BranchesTElemCategoryVendor BranchesTElemCategory = "vendor"

// Representation of security advisory information as a JSON document.
type CSAF struct {
	// Captures the meta-data about this document describing a particular set of
	// security advisories.
	Document CSAFDocument `json:"document"`

	// Is a container for all fully qualified product names that can be referenced
	// elsewhere in the document.
	ProductTree *CSAFProductTree `json:"product_tree,omitempty,omitzero"`

	// Represents a list of all relevant vulnerability information items.
	Vulnerabilities []CSAFVulnerabilitiesElem `json:"vulnerabilities,omitempty,omitzero"`
}

// Captures the meta-data about this document describing a particular set of
// security advisories.
type CSAFDocument struct {
	// Contains a list of acknowledgment elements associated with the whole document.
	Acknowledgments AcknowledgmentsT `json:"acknowledgments,omitempty,omitzero"`

	// Is a vehicle that is provided by the document producer to convey the urgency
	// and criticality with which the one or more vulnerabilities reported should be
	// addressed. It is a document-level metric and applied to the document as a whole
	// - not any specific vulnerability. The range of values in this field is defined
	// according to the document producer's policies and procedures.
	AggregateSeverity *CSAFDocumentAggregateSeverity `json:"aggregate_severity,omitempty,omitzero"`

	// Defines a short canonical name, chosen by the document producer, which will
	// inform the end user as to the category of document.
	Category string `json:"category"`

	// Gives the version of the CSAF specification which the document was generated
	// for.
	CSAFVersion CSAFDocumentCSAFVersion `json:"csaf_version"`

	// Describe any constraints on how this document might be shared.
	Distribution *CSAFDocumentDistribution `json:"distribution,omitempty,omitzero"`

	// Identifies the language used by this document, corresponding to IETF BCP 47 /
	// RFC 5646.
	Lang *LangT `json:"lang,omitempty,omitzero"`

	// Holds notes associated with the whole document.
	Notes NotesT `json:"notes,omitempty,omitzero"`

	// Provides information about the publisher of the document.
	Publisher CSAFDocumentPublisher `json:"publisher"`

	// Holds a list of references associated with the whole document.
	References ReferencesT `json:"references,omitempty,omitzero"`

	// If this copy of the document is a translation then the value of this property
	// describes from which language this document was translated.
	SourceLang *LangT `json:"source_lang,omitempty,omitzero"`

	// This SHOULD be a canonical name for the document, and sufficiently unique to
	// distinguish it from similar documents.
	Title string `json:"title"`

	// Is a container designated to hold all management attributes necessary to track
	// a CSAF document as a whole.
	Tracking CSAFDocumentTracking `json:"tracking"`
}

// Is a vehicle that is provided by the document producer to convey the urgency and
// criticality with which the one or more vulnerabilities reported should be
// addressed. It is a document-level metric and applied to the document as a whole
// - not any specific vulnerability. The range of values in this field is defined
// according to the document producer's policies and procedures.
type CSAFDocumentAggregateSeverity struct {
	// Points to the namespace so referenced.
	Namespace *string `json:"namespace,omitempty,omitzero"`

	// Provides a severity which is independent of - and in addition to - any other
	// standard metric for determining the impact or severity of a given vulnerability
	// (such as CVSS).
	Text string `json:"text"`
}

type CSAFDocumentCSAFVersion string

const CSAFDocumentCSAFVersionA20 CSAFDocumentCSAFVersion = "2.0"

// Describe any constraints on how this document might be shared.
type CSAFDocumentDistribution struct {
	// Provides a textual description of additional constraints.
	Text *string `json:"text,omitempty,omitzero"`

	// Provides details about the TLP classification of the document.
	TLP *CSAFDocumentDistributionTLP `json:"tlp,omitempty,omitzero"`
}

// Provides details about the TLP classification of the document.
type CSAFDocumentDistributionTLP struct {
	// Provides the TLP label of the document.
	Label CSAFDocumentDistributionTLPLabel `json:"label"`

	// Provides a URL where to find the textual description of the TLP version which
	// is used in this document. Default is the URL to the definition by FIRST.
	URL string `json:"url,omitempty,omitzero"`
}

type CSAFDocumentDistributionTLPLabel string

const CSAFDocumentDistributionTLPLabelAMBER CSAFDocumentDistributionTLPLabel = "AMBER"
const CSAFDocumentDistributionTLPLabelGREEN CSAFDocumentDistributionTLPLabel = "GREEN"
const CSAFDocumentDistributionTLPLabelRED CSAFDocumentDistributionTLPLabel = "RED"
const CSAFDocumentDistributionTLPLabelWHITE CSAFDocumentDistributionTLPLabel = "WHITE"

// Provides information about the publisher of the document.
type CSAFDocumentPublisher struct {
	// Provides information about the category of publisher releasing the document.
	Category CSAFDocumentPublisherCategory `json:"category"`

	// Information on how to contact the publisher, possibly including details such as
	// web sites, email addresses, phone numbers, and postal mail addresses.
	ContactDetails *string `json:"contact_details,omitempty,omitzero"`

	// Provides information about the authority of the issuing party to release the
	// document, in particular, the party's constituency and responsibilities or other
	// obligations.
	IssuingAuthority *string `json:"issuing_authority,omitempty,omitzero"`

	// Contains the name of the issuing party.
	Name string `json:"name"`

	// Contains a URL which is under control of the issuing party and can be used as a
	// globally unique identifier for that issuing party.
	Namespace string `json:"namespace"`
}

type CSAFDocumentPublisherCategory string

const CSAFDocumentPublisherCategoryCoordinator CSAFDocumentPublisherCategory = "coordinator"
const CSAFDocumentPublisherCategoryDiscoverer CSAFDocumentPublisherCategory = "discoverer"
const CSAFDocumentPublisherCategoryOther CSAFDocumentPublisherCategory = "other"
const CSAFDocumentPublisherCategoryTranslator CSAFDocumentPublisherCategory = "translator"
const CSAFDocumentPublisherCategoryUser CSAFDocumentPublisherCategory = "user"
const CSAFDocumentPublisherCategoryVendor CSAFDocumentPublisherCategory = "vendor"

// Is a container designated to hold all management attributes necessary to track a
// CSAF document as a whole.
type CSAFDocumentTracking struct {
	// Contains a list of alternate names for the same document.
	Aliases []string `json:"aliases,omitempty,omitzero"`

	// The date when the current revision of this document was released
	CurrentReleaseDate DateTime `json:"current_release_date"`

	// Is a container to hold all elements related to the generation of the document.
	// These items will reference when the document was actually created, including
	// the date it was generated and the entity that generated it.
	Generator *CSAFDocumentTrackingGenerator `json:"generator,omitempty,omitzero"`

	// The ID is a simple label that provides for a wide range of numbering values,
	// types, and schemes. Its value SHOULD be assigned and maintained by the original
	// document issuing authority.
	ID string `json:"id"`

	// The date when this document was first published.
	InitialReleaseDate DateTime `json:"initial_release_date"`

	// Holds one revision item for each version of the CSAF document, including the
	// initial one.
	RevisionHistory []CSAFDocumentTrackingRevisionHistoryElem `json:"revision_history"`

	// Defines the draft status of the document.
	Status CSAFDocumentTrackingStatus `json:"status"`

	// Version corresponds to the JSON schema field "version".
	Version VersionT `json:"version"`
}

// Is a container to hold all elements related to the generation of the document.
// These items will reference when the document was actually created, including the
// date it was generated and the entity that generated it.
type CSAFDocumentTrackingGenerator struct {
	// This SHOULD be the current date that the document was generated. Because
	// documents are often generated internally by a document producer and exist for a
	// nonzero amount of time before being released, this field MAY be different from
	// the Initial Release Date and Current Release Date.
	Date *DateTime `json:"date,omitempty,omitzero"`

	// Contains information about the engine that generated the CSAF document.
	Engine CSAFDocumentTrackingGeneratorEngine `json:"engine"`
}

// Contains information about the engine that generated the CSAF document.
type CSAFDocumentTrackingGeneratorEngine struct {
	// Represents the name of the engine that generated the CSAF document.
	Name string `json:"name"`

	// Contains the version of the engine that generated the CSAF document.
	Version *string `json:"version,omitempty,omitzero"`
}

// Contains all the information elements required to track the evolution of a CSAF
// document.
type CSAFDocumentTrackingRevisionHistoryElem struct {
	// The date of the revision entry
	Date DateTime `json:"date"`

	// Contains the version string used in an existing document with the same content.
	LegacyVersion *string `json:"legacy_version,omitempty,omitzero"`

	// Number corresponds to the JSON schema field "number".
	Number VersionT `json:"number"`

	// Holds a single non-empty string representing a short description of the
	// changes.
	Summary string `json:"summary"`
}

type CSAFDocumentTrackingStatus string

const CSAFDocumentTrackingStatusDraft CSAFDocumentTrackingStatus = "draft"
const CSAFDocumentTrackingStatusFinal CSAFDocumentTrackingStatus = "final"
const CSAFDocumentTrackingStatusInterim CSAFDocumentTrackingStatus = "interim"

// Is a container for all fully qualified product names that can be referenced
// elsewhere in the document.
type CSAFProductTree struct {
	// Branches corresponds to the JSON schema field "branches".
	Branches BranchesT `json:"branches,omitempty,omitzero"`

	// Contains a list of full product names.
	FullProductNames []FullProductNameT `json:"full_product_names,omitempty,omitzero"`

	// Contains a list of product groups.
	ProductGroups []CSAFProductTreeProductGroupsElem `json:"product_groups,omitempty,omitzero"`

	// Contains a list of relationships.
	Relationships []CSAFProductTreeRelationshipsElem `json:"relationships,omitempty,omitzero"`
}

// Defines a new logical group of products that can then be referred to in other
// parts of the document to address a group of products with a single identifier.
type CSAFProductTreeProductGroupsElem struct {
	// GroupID corresponds to the JSON schema field "group_id".
	GroupID ProductGroupIDT `json:"group_id"`

	// Lists the product_ids of those products which known as one group in the
	// document.
	ProductIds []ProductIDT `json:"product_ids"`

	// Gives a short, optional description of the group.
	Summary *string `json:"summary,omitempty,omitzero"`
}

// Establishes a link between two existing full_product_name_t elements, allowing
// the document producer to define a combination of two products that form a new
// full_product_name entry.
type CSAFProductTreeRelationshipsElem struct {
	// Defines the category of relationship for the referenced component.
	Category CSAFProductTreeRelationshipsElemCategory `json:"category"`

	// FullProductName corresponds to the JSON schema field "full_product_name".
	FullProductName FullProductNameT `json:"full_product_name"`

	// Holds a Product ID that refers to the Full Product Name element, which is
	// referenced as the first element of the relationship.
	ProductReference ProductIDT `json:"product_reference"`

	// Holds a Product ID that refers to the Full Product Name element, which is
	// referenced as the second element of the relationship.
	RelatesToProductReference ProductIDT `json:"relates_to_product_reference"`
}

type CSAFProductTreeRelationshipsElemCategory string

const CSAFProductTreeRelationshipsElemCategoryDefaultComponentOf CSAFProductTreeRelationshipsElemCategory = "default_component_of"
const CSAFProductTreeRelationshipsElemCategoryExternalComponentOf CSAFProductTreeRelationshipsElemCategory = "external_component_of"
const CSAFProductTreeRelationshipsElemCategoryInstalledOn CSAFProductTreeRelationshipsElemCategory = "installed_on"
const CSAFProductTreeRelationshipsElemCategoryInstalledWith CSAFProductTreeRelationshipsElemCategory = "installed_with"
const CSAFProductTreeRelationshipsElemCategoryOptionalComponentOf CSAFProductTreeRelationshipsElemCategory = "optional_component_of"

// Is a container for the aggregation of all fields that are related to a single
// vulnerability in the document.
type CSAFVulnerabilitiesElem struct {
	// Contains a list of acknowledgment elements associated with this vulnerability
	// item.
	Acknowledgments AcknowledgmentsT `json:"acknowledgments,omitempty,omitzero"`

	// Holds the MITRE standard Common Vulnerabilities and Exposures (CVE) tracking
	// number for the vulnerability.
	CVE *string `json:"cve,omitempty,omitzero"`

	// Holds the MITRE standard Common Weakness Enumeration (CWE) for the weakness
	// associated.
	CWE *CSAFVulnerabilitiesElemCWE `json:"cwe,omitempty,omitzero"`

	// Holds the date and time the vulnerability was originally discovered.
	DiscoveryDate *DateTime `json:"discovery_date,omitempty,omitzero"`

	// Contains a list of machine readable flags.
	Flags []CSAFVulnerabilitiesElemFlagsElem `json:"flags,omitempty,omitzero"`

	// Represents a list of unique labels or tracking IDs for the vulnerability (if
	// such information exists).
	Ids []CSAFVulnerabilitiesElemIdsElem `json:"ids,omitempty,omitzero"`

	// Contains a list of involvements.
	Involvements []CSAFVulnerabilitiesElemInvolvementsElem `json:"involvements,omitempty,omitzero"`

	// Holds notes associated with this vulnerability item.
	Notes NotesT `json:"notes,omitempty,omitzero"`

	// Contains different lists of product_ids which provide details on the status of
	// the referenced product related to the current vulnerability.
	ProductStatus *CSAFVulnerabilitiesElemProductStatus `json:"product_status,omitempty,omitzero"`

	// Holds a list of references associated with this vulnerability item.
	References ReferencesT `json:"references,omitempty,omitzero"`

	// Holds the date and time the vulnerability was originally released into the
	// wild.
	ReleaseDate *DateTime `json:"release_date,omitempty,omitzero"`

	// Contains a list of remediations.
	Remediations []CSAFVulnerabilitiesElemRemediationsElem `json:"remediations,omitempty,omitzero"`

	// contains score objects for the current vulnerability.
	Scores []CSAFVulnerabilitiesElemScoresElem `json:"scores,omitempty,omitzero"`

	// Contains information about a vulnerability that can change with time.
	Threats []CSAFVulnerabilitiesElemThreatsElem `json:"threats,omitempty,omitzero"`

	// Gives the document producer the ability to apply a canonical name or title to
	// the vulnerability.
	Title *string `json:"title,omitempty,omitzero"`
}

// Holds the MITRE standard Common Weakness Enumeration (CWE) for the weakness
// associated.
type CSAFVulnerabilitiesElemCWE struct {
	// Holds the ID for the weakness associated.
	ID string `json:"id"`

	// Holds the full name of the weakness as given in the CWE specification.
	Name string `json:"name"`
}

// Contains product specific information in regard to this vulnerability as a
// single machine readable flag.
type CSAFVulnerabilitiesElemFlagsElem struct {
	// Contains the date when assessment was done or the flag was assigned.
	Date *DateTime `json:"date,omitempty,omitzero"`

	// GroupIds corresponds to the JSON schema field "group_ids".
	GroupIds ProductGroupsT `json:"group_ids,omitempty,omitzero"`

	// Specifies the machine readable label.
	Label CSAFVulnerabilitiesElemFlagsElemLabel `json:"label"`

	// ProductIds corresponds to the JSON schema field "product_ids".
	ProductIds ProductsT `json:"product_ids,omitempty,omitzero"`
}

type CSAFVulnerabilitiesElemFlagsElemLabel string

const CSAFVulnerabilitiesElemFlagsElemLabelComponentNotPresent CSAFVulnerabilitiesElemFlagsElemLabel = "component_not_present"
const CSAFVulnerabilitiesElemFlagsElemLabelInlineMitigationsAlreadyExist CSAFVulnerabilitiesElemFlagsElemLabel = "inline_mitigations_already_exist"
const CSAFVulnerabilitiesElemFlagsElemLabelVulnerableCodeCannotBeControlledByAdversary CSAFVulnerabilitiesElemFlagsElemLabel = "vulnerable_code_cannot_be_controlled_by_adversary"
const CSAFVulnerabilitiesElemFlagsElemLabelVulnerableCodeNotInExecutePath CSAFVulnerabilitiesElemFlagsElemLabel = "vulnerable_code_not_in_execute_path"
const CSAFVulnerabilitiesElemFlagsElemLabelVulnerableCodeNotPresent CSAFVulnerabilitiesElemFlagsElemLabel = "vulnerable_code_not_present"

// Contains a single unique label or tracking ID for the vulnerability.
type CSAFVulnerabilitiesElemIdsElem struct {
	// Indicates the name of the vulnerability tracking or numbering system.
	SystemName string `json:"system_name"`

	// Is unique label or tracking ID for the vulnerability (if such information
	// exists).
	Text string `json:"text"`
}

// Is a container, that allows the document producers to comment on the level of
// involvement (or engagement) of themselves or third parties in the vulnerability
// identification, scoping, and remediation process.
type CSAFVulnerabilitiesElemInvolvementsElem struct {
	// Holds the date and time of the involvement entry.
	Date *DateTime `json:"date,omitempty,omitzero"`

	// Defines the category of the involved party.
	Party CSAFVulnerabilitiesElemInvolvementsElemParty `json:"party"`

	// Defines contact status of the involved party.
	Status CSAFVulnerabilitiesElemInvolvementsElemStatus `json:"status"`

	// Contains additional context regarding what is going on.
	Summary *string `json:"summary,omitempty,omitzero"`
}

type CSAFVulnerabilitiesElemInvolvementsElemParty string

const CSAFVulnerabilitiesElemInvolvementsElemPartyCoordinator CSAFVulnerabilitiesElemInvolvementsElemParty = "coordinator"
const CSAFVulnerabilitiesElemInvolvementsElemPartyDiscoverer CSAFVulnerabilitiesElemInvolvementsElemParty = "discoverer"
const CSAFVulnerabilitiesElemInvolvementsElemPartyOther CSAFVulnerabilitiesElemInvolvementsElemParty = "other"
const CSAFVulnerabilitiesElemInvolvementsElemPartyUser CSAFVulnerabilitiesElemInvolvementsElemParty = "user"
const CSAFVulnerabilitiesElemInvolvementsElemPartyVendor CSAFVulnerabilitiesElemInvolvementsElemParty = "vendor"

type CSAFVulnerabilitiesElemInvolvementsElemStatus string

const CSAFVulnerabilitiesElemInvolvementsElemStatusCompleted CSAFVulnerabilitiesElemInvolvementsElemStatus = "completed"
const CSAFVulnerabilitiesElemInvolvementsElemStatusContactAttempted CSAFVulnerabilitiesElemInvolvementsElemStatus = "contact_attempted"
const CSAFVulnerabilitiesElemInvolvementsElemStatusDisputed CSAFVulnerabilitiesElemInvolvementsElemStatus = "disputed"
const CSAFVulnerabilitiesElemInvolvementsElemStatusInProgress CSAFVulnerabilitiesElemInvolvementsElemStatus = "in_progress"
const CSAFVulnerabilitiesElemInvolvementsElemStatusNotContacted CSAFVulnerabilitiesElemInvolvementsElemStatus = "not_contacted"
const CSAFVulnerabilitiesElemInvolvementsElemStatusOpen CSAFVulnerabilitiesElemInvolvementsElemStatus = "open"

// Contains different lists of product_ids which provide details on the status of
// the referenced product related to the current vulnerability.
type CSAFVulnerabilitiesElemProductStatus struct {
	// These are the first versions of the releases known to be affected by the
	// vulnerability.
	FirstAffected ProductsT `json:"first_affected,omitempty,omitzero"`

	// These versions contain the first fix for the vulnerability but may not be the
	// recommended fixed versions.
	FirstFixed ProductsT `json:"first_fixed,omitempty,omitzero"`

	// These versions contain a fix for the vulnerability but may not be the
	// recommended fixed versions.
	Fixed ProductsT `json:"fixed,omitempty,omitzero"`

	// These versions are known to be affected by the vulnerability.
	KnownAffected ProductsT `json:"known_affected,omitempty,omitzero"`

	// These versions are known not to be affected by the vulnerability.
	KnownNotAffected ProductsT `json:"known_not_affected,omitempty,omitzero"`

	// These are the last versions in a release train known to be affected by the
	// vulnerability. Subsequently released versions would contain a fix for the
	// vulnerability.
	LastAffected ProductsT `json:"last_affected,omitempty,omitzero"`

	// These versions have a fix for the vulnerability and are the vendor-recommended
	// versions for fixing the vulnerability.
	Recommended ProductsT `json:"recommended,omitempty,omitzero"`

	// It is not known yet whether these versions are or are not affected by the
	// vulnerability. However, it is still under investigation - the result will be
	// provided in a later release of the document.
	UnderInvestigation ProductsT `json:"under_investigation,omitempty,omitzero"`
}

// Specifies details on how to handle (and presumably, fix) a vulnerability.
type CSAFVulnerabilitiesElemRemediationsElem struct {
	// Specifies the category which this remediation belongs to.
	Category CSAFVulnerabilitiesElemRemediationsElemCategory `json:"category"`

	// Contains the date from which the remediation is available.
	Date *DateTime `json:"date,omitempty,omitzero"`

	// Contains a thorough human-readable discussion of the remediation.
	Details string `json:"details"`

	// Contains a list of entitlements.
	Entitlements []string `json:"entitlements,omitempty,omitzero"`

	// GroupIds corresponds to the JSON schema field "group_ids".
	GroupIds ProductGroupsT `json:"group_ids,omitempty,omitzero"`

	// ProductIds corresponds to the JSON schema field "product_ids".
	ProductIds ProductsT `json:"product_ids,omitempty,omitzero"`

	// Provides information on category of restart is required by this remediation to
	// become effective.
	RestartRequired *CSAFVulnerabilitiesElemRemediationsElemRestartRequired `json:"restart_required,omitempty,omitzero"`

	// Contains the URL where to obtain the remediation.
	URL *string `json:"url,omitempty,omitzero"`
}

type CSAFVulnerabilitiesElemRemediationsElemCategory string

const CSAFVulnerabilitiesElemRemediationsElemCategoryMitigation CSAFVulnerabilitiesElemRemediationsElemCategory = "mitigation"
const CSAFVulnerabilitiesElemRemediationsElemCategoryNoFixPlanned CSAFVulnerabilitiesElemRemediationsElemCategory = "no_fix_planned"
const CSAFVulnerabilitiesElemRemediationsElemCategoryNoneAvailable CSAFVulnerabilitiesElemRemediationsElemCategory = "none_available"
const CSAFVulnerabilitiesElemRemediationsElemCategoryVendorFix CSAFVulnerabilitiesElemRemediationsElemCategory = "vendor_fix"
const CSAFVulnerabilitiesElemRemediationsElemCategoryWorkaround CSAFVulnerabilitiesElemRemediationsElemCategory = "workaround"

// Provides information on category of restart is required by this remediation to
// become effective.
type CSAFVulnerabilitiesElemRemediationsElemRestartRequired struct {
	// Specifies what category of restart is required by this remediation to become
	// effective.
	Category CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory `json:"category"`

	// Provides additional information for the restart. This can include details on
	// procedures, scope or impact.
	Details *string `json:"details,omitempty,omitzero"`
}

type CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory string

const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryConnected CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "connected"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryDependencies CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "dependencies"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryMachine CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "machine"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryNone CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "none"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryParent CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "parent"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryService CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "service"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategorySystem CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "system"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryVulnerableComponent CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "vulnerable_component"
const CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategoryZone CSAFVulnerabilitiesElemRemediationsElemRestartRequiredCategory = "zone"

// specifies information about (at least one) score of the vulnerability and for
// which products the given value applies.
type CSAFVulnerabilitiesElemScoresElem struct {
	// CVSSV2 corresponds to the JSON schema field "cvss_v2".
	CVSSV2 *CVSSV20 `json:"cvss_v2,omitempty,omitzero"`

	// CVSSV3 corresponds to the JSON schema field "cvss_v3".
	CVSSV3 CVSSV3 `json:"cvss_v3,omitempty,omitzero"`

	// Products corresponds to the JSON schema field "products".
	Products ProductsT `json:"products"`
}

// Contains the vulnerability kinetic information. This information can change as
// the vulnerability ages and new information becomes available.
type CSAFVulnerabilitiesElemThreatsElem struct {
	// Categorizes the threat according to the rules of the specification.
	Category CSAFVulnerabilitiesElemThreatsElemCategory `json:"category"`

	// Contains the date when the assessment was done or the threat appeared.
	Date *DateTime `json:"date,omitempty,omitzero"`

	// Represents a thorough human-readable discussion of the threat.
	Details string `json:"details"`

	// GroupIds corresponds to the JSON schema field "group_ids".
	GroupIds ProductGroupsT `json:"group_ids,omitempty,omitzero"`

	// ProductIds corresponds to the JSON schema field "product_ids".
	ProductIds ProductsT `json:"product_ids,omitempty,omitzero"`
}

type CSAFVulnerabilitiesElemThreatsElemCategory string

const CSAFVulnerabilitiesElemThreatsElemCategoryExploitStatus CSAFVulnerabilitiesElemThreatsElemCategory = "exploit_status"
const CSAFVulnerabilitiesElemThreatsElemCategoryImpact CSAFVulnerabilitiesElemThreatsElemCategory = "impact"
const CSAFVulnerabilitiesElemThreatsElemCategoryTargetSet CSAFVulnerabilitiesElemThreatsElemCategory = "target_set"

// Specifies information about the product and assigns the product_id.
type FullProductNameT struct {
	// The value should be the product's full canonical name, including version number
	// and other attributes, as it would be used in a human-friendly document.
	Name string `json:"name"`

	// ProductID corresponds to the JSON schema field "product_id".
	ProductID ProductIDT `json:"product_id"`

	// Provides at least one method which aids in identifying the product in an asset
	// database.
	ProductIdentificationHelper *FullProductNameTProductIdentificationHelper `json:"product_identification_helper,omitempty,omitzero"`
}

// Provides at least one method which aids in identifying the product in an asset
// database.
type FullProductNameTProductIdentificationHelper struct {
	// The Common Platform Enumeration (CPE) attribute refers to a method for naming
	// platforms external to this specification.
	CPE *string `json:"cpe,omitempty,omitzero"`

	// Contains a list of cryptographic hashes usable to identify files.
	Hashes []FullProductNameTProductIdentificationHelperHashesElem `json:"hashes,omitempty,omitzero"`

	// Contains a list of parts, or full model numbers.
	ModelNumbers []string `json:"model_numbers,omitempty,omitzero"`

	// The package URL (purl) attribute refers to a method for reliably identifying
	// and locating software packages external to this specification.
	Purl *string `json:"purl,omitempty,omitzero"`

	// Contains a list of URLs where SBOMs for this product can be retrieved.
	SbomUrls []string `json:"sbom_urls,omitempty,omitzero"`

	// Contains a list of parts, or full serial numbers.
	SerialNumbers []string `json:"serial_numbers,omitempty,omitzero"`

	// Contains a list of parts, or full stock keeping units.
	Skus []string `json:"skus,omitempty,omitzero"`

	// Contains a list of identifiers which are either vendor-specific or derived from
	// a standard not yet supported.
	XGenericUris []FullProductNameTProductIdentificationHelperXGenericUrisElem `json:"x_generic_uris,omitempty,omitzero"`
}

// Contains all information to identify a file based on its cryptographic hash
// values.
type FullProductNameTProductIdentificationHelperHashesElem struct {
	// Contains a list of cryptographic hashes for this file.
	FileHashes []FullProductNameTProductIdentificationHelperHashesElemFileHashesElem `json:"file_hashes"`

	// Contains the name of the file which is identified by the hash values.
	Filename string `json:"filename"`
}

// Contains one hash value and algorithm of the file to be identified.
type FullProductNameTProductIdentificationHelperHashesElemFileHashesElem struct {
	// Contains the name of the cryptographic hash algorithm used to calculate the
	// value.
	Algorithm string `json:"algorithm"`

	// Contains the cryptographic hash value in hexadecimal representation.
	Value string `json:"value"`
}

// Provides a generic extension point for any identifier which is either
// vendor-specific or derived from a standard not yet supported.
type FullProductNameTProductIdentificationHelperXGenericUrisElem struct {
	// Refers to a URL which provides the name and knowledge about the specification
	// used or is the namespace in which these values are valid.
	Namespace string `json:"namespace"`

	// Contains the identifier itself.
	URI string `json:"uri"`
}

// Identifies a language, corresponding to IETF BCP 47 / RFC 5646. See IETF
// language registry:
// https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
type LangT string

// Contains notes which are specific to the current context.
type NotesT []struct {
	// Indicate who is intended to read it.
	Audience *string `json:"audience,omitempty,omitzero"`

	// Choice of what kind of note this is.
	Category NotesTElemCategory `json:"category"`

	// The contents of the note. Content varies depending on type.
	Text string `json:"text"`

	// Provides a concise description of what is contained in the text of the note.
	Title *string `json:"title,omitempty,omitzero"`
}

type NotesTElemCategory string

const NotesTElemCategoryDescription NotesTElemCategory = "description"
const NotesTElemCategoryDetails NotesTElemCategory = "details"
const NotesTElemCategoryFaq NotesTElemCategory = "faq"
const NotesTElemCategoryGeneral NotesTElemCategory = "general"
const NotesTElemCategoryLegalDisclaimer NotesTElemCategory = "legal_disclaimer"
const NotesTElemCategoryOther NotesTElemCategory = "other"
const NotesTElemCategorySummary NotesTElemCategory = "summary"

// Token required to identify a group of products so that it can be referred to
// from other parts in the document. There is no predefined or required format for
// the product_group_id as long as it uniquely identifies a group in the context of
// the current document.
type ProductGroupIDT string

// Specifies a list of product_group_ids to give context to the parent item.
type ProductGroupsT []ProductGroupIDT

// Token required to identify a full_product_name so that it can be referred to
// from other parts in the document. There is no predefined or required format for
// the product_id as long as it uniquely identifies a product in the context of the
// current document.
type ProductIDT string

// Specifies a list of product_ids to give context to the parent item.
type ProductsT []ProductIDT

// Holds a list of references.
type ReferencesT []struct {
	// Indicates whether the reference points to the same document or vulnerability in
	// focus (depending on scope) or to an external resource.
	Category ReferencesTElemCategory `json:"category,omitempty,omitzero"`

	// Indicates what this reference refers to.
	Summary string `json:"summary"`

	// Provides the URL for the reference.
	URL string `json:"url"`
}

type ReferencesTElemCategory string

const ReferencesTElemCategoryExternal ReferencesTElemCategory = "external"
const ReferencesTElemCategorySelf ReferencesTElemCategory = "self"

// Specifies a version string to denote clearly the evolution of the content of the
// document. Format must be either integer or semantic versioning.
type VersionT string
