// SPDX-License-Identifier: Apache-2.0

// Code generated by go-jsonschema and internal/generate/prepare_v20_model.py. DO NOT EDIT.

package v20

type AccessComplexityType string

const AccessComplexityTypeHIGH AccessComplexityType = "HIGH"
const AccessComplexityTypeLOW AccessComplexityType = "LOW"
const AccessComplexityTypeMEDIUM AccessComplexityType = "MEDIUM"

type AccessVectorType string

const AccessVectorTypeADJACENTNETWORK AccessVectorType = "ADJACENT_NETWORK"
const AccessVectorTypeLOCAL AccessVectorType = "LOCAL"
const AccessVectorTypeNETWORK AccessVectorType = "NETWORK"

type AttackComplexityType string

const AttackComplexityTypeHIGH AttackComplexityType = "HIGH"
const AttackComplexityTypeLOW AttackComplexityType = "LOW"

type AttackVectorType string

const AttackVectorTypeADJACENTNETWORK AttackVectorType = "ADJACENT_NETWORK"
const AttackVectorTypeLOCAL AttackVectorType = "LOCAL"
const AttackVectorTypeNETWORK AttackVectorType = "NETWORK"
const AttackVectorTypePHYSICAL AttackVectorType = "PHYSICAL"

type AuthenticationType string

const AuthenticationTypeMULTIPLE AuthenticationType = "MULTIPLE"
const AuthenticationTypeNONE AuthenticationType = "NONE"
const AuthenticationTypeSINGLE AuthenticationType = "SINGLE"

type CVSSV20 struct {
	// AccessComplexity corresponds to the JSON schema field "accessComplexity".
	AccessComplexity *AccessComplexityType `json:"accessComplexity,omitempty,omitzero"`

	// AccessVector corresponds to the JSON schema field "accessVector".
	AccessVector *AccessVectorType `json:"accessVector,omitempty,omitzero"`

	// Authentication corresponds to the JSON schema field "authentication".
	Authentication *AuthenticationType `json:"authentication,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// CollateralDamagePotential corresponds to the JSON schema field
	// "collateralDamagePotential".
	CollateralDamagePotential *CollateralDamagePotentialType `json:"collateralDamagePotential,omitempty,omitzero"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// Exploitability corresponds to the JSON schema field "exploitability".
	Exploitability *ExploitabilityType `json:"exploitability,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ReportConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// TargetDistribution corresponds to the JSON schema field "targetDistribution".
	TargetDistribution *TargetDistributionType `json:"targetDistribution,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV20Version `json:"version"`
}

type CVSSV20Version string

const CVSSV20VersionA20 CVSSV20Version = "2.0"

type CVSSV30 struct {
	// AttackComplexity corresponds to the JSON schema field "attackComplexity".
	AttackComplexity *AttackComplexityType `json:"attackComplexity,omitempty,omitzero"`

	// AttackVector corresponds to the JSON schema field "attackVector".
	AttackVector *AttackVectorType `json:"attackVector,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType_1 `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity SeverityType `json:"baseSeverity"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType_1 `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// EnvironmentalSeverity corresponds to the JSON schema field
	// "environmentalSeverity".
	EnvironmentalSeverity *SeverityType `json:"environmentalSeverity,omitempty,omitzero"`

	// ExploitCodeMaturity corresponds to the JSON schema field "exploitCodeMaturity".
	ExploitCodeMaturity *ExploitCodeMaturityType `json:"exploitCodeMaturity,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType_1 `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// ModifiedAttackComplexity corresponds to the JSON schema field
	// "modifiedAttackComplexity".
	ModifiedAttackComplexity *ModifiedAttackComplexityType `json:"modifiedAttackComplexity,omitempty,omitzero"`

	// ModifiedAttackVector corresponds to the JSON schema field
	// "modifiedAttackVector".
	ModifiedAttackVector *ModifiedAttackVectorType `json:"modifiedAttackVector,omitempty,omitzero"`

	// ModifiedAvailabilityImpact corresponds to the JSON schema field
	// "modifiedAvailabilityImpact".
	ModifiedAvailabilityImpact *ModifiedCiaType `json:"modifiedAvailabilityImpact,omitempty,omitzero"`

	// ModifiedConfidentialityImpact corresponds to the JSON schema field
	// "modifiedConfidentialityImpact".
	ModifiedConfidentialityImpact *ModifiedCiaType `json:"modifiedConfidentialityImpact,omitempty,omitzero"`

	// ModifiedIntegrityImpact corresponds to the JSON schema field
	// "modifiedIntegrityImpact".
	ModifiedIntegrityImpact *ModifiedCiaType `json:"modifiedIntegrityImpact,omitempty,omitzero"`

	// ModifiedPrivilegesRequired corresponds to the JSON schema field
	// "modifiedPrivilegesRequired".
	ModifiedPrivilegesRequired *ModifiedPrivilegesRequiredType `json:"modifiedPrivilegesRequired,omitempty,omitzero"`

	// ModifiedScope corresponds to the JSON schema field "modifiedScope".
	ModifiedScope *ModifiedScopeType `json:"modifiedScope,omitempty,omitzero"`

	// ModifiedUserInteraction corresponds to the JSON schema field
	// "modifiedUserInteraction".
	ModifiedUserInteraction *ModifiedUserInteractionType `json:"modifiedUserInteraction,omitempty,omitzero"`

	// PrivilegesRequired corresponds to the JSON schema field "privilegesRequired".
	PrivilegesRequired *PrivilegesRequiredType `json:"privilegesRequired,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// Scope corresponds to the JSON schema field "scope".
	Scope *ScopeType `json:"scope,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// TemporalSeverity corresponds to the JSON schema field "temporalSeverity".
	TemporalSeverity *SeverityType `json:"temporalSeverity,omitempty,omitzero"`

	// UserInteraction corresponds to the JSON schema field "userInteraction".
	UserInteraction *UserInteractionType `json:"userInteraction,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV30Version `json:"version"`
}

type CVSSV30Version string

const CVSSV30VersionA30 CVSSV30Version = "3.0"

type CVSSV31 struct {
	// AttackComplexity corresponds to the JSON schema field "attackComplexity".
	AttackComplexity *AttackComplexityType `json:"attackComplexity,omitempty,omitzero"`

	// AttackVector corresponds to the JSON schema field "attackVector".
	AttackVector *AttackVectorType `json:"attackVector,omitempty,omitzero"`

	// AvailabilityImpact corresponds to the JSON schema field "availabilityImpact".
	AvailabilityImpact *CiaType_1 `json:"availabilityImpact,omitempty,omitzero"`

	// AvailabilityRequirement corresponds to the JSON schema field
	// "availabilityRequirement".
	AvailabilityRequirement *CiaRequirementType `json:"availabilityRequirement,omitempty,omitzero"`

	// BaseScore corresponds to the JSON schema field "baseScore".
	BaseScore ScoreType `json:"baseScore"`

	// BaseSeverity corresponds to the JSON schema field "baseSeverity".
	BaseSeverity SeverityType `json:"baseSeverity"`

	// ConfidentialityImpact corresponds to the JSON schema field
	// "confidentialityImpact".
	ConfidentialityImpact *CiaType_1 `json:"confidentialityImpact,omitempty,omitzero"`

	// ConfidentialityRequirement corresponds to the JSON schema field
	// "confidentialityRequirement".
	ConfidentialityRequirement *CiaRequirementType `json:"confidentialityRequirement,omitempty,omitzero"`

	// EnvironmentalScore corresponds to the JSON schema field "environmentalScore".
	EnvironmentalScore *ScoreType `json:"environmentalScore,omitempty,omitzero"`

	// EnvironmentalSeverity corresponds to the JSON schema field
	// "environmentalSeverity".
	EnvironmentalSeverity *SeverityType `json:"environmentalSeverity,omitempty,omitzero"`

	// ExploitCodeMaturity corresponds to the JSON schema field "exploitCodeMaturity".
	ExploitCodeMaturity *ExploitCodeMaturityType `json:"exploitCodeMaturity,omitempty,omitzero"`

	// IntegrityImpact corresponds to the JSON schema field "integrityImpact".
	IntegrityImpact *CiaType_1 `json:"integrityImpact,omitempty,omitzero"`

	// IntegrityRequirement corresponds to the JSON schema field
	// "integrityRequirement".
	IntegrityRequirement *CiaRequirementType `json:"integrityRequirement,omitempty,omitzero"`

	// ModifiedAttackComplexity corresponds to the JSON schema field
	// "modifiedAttackComplexity".
	ModifiedAttackComplexity *ModifiedAttackComplexityType `json:"modifiedAttackComplexity,omitempty,omitzero"`

	// ModifiedAttackVector corresponds to the JSON schema field
	// "modifiedAttackVector".
	ModifiedAttackVector *ModifiedAttackVectorType `json:"modifiedAttackVector,omitempty,omitzero"`

	// ModifiedAvailabilityImpact corresponds to the JSON schema field
	// "modifiedAvailabilityImpact".
	ModifiedAvailabilityImpact *ModifiedCiaType `json:"modifiedAvailabilityImpact,omitempty,omitzero"`

	// ModifiedConfidentialityImpact corresponds to the JSON schema field
	// "modifiedConfidentialityImpact".
	ModifiedConfidentialityImpact *ModifiedCiaType `json:"modifiedConfidentialityImpact,omitempty,omitzero"`

	// ModifiedIntegrityImpact corresponds to the JSON schema field
	// "modifiedIntegrityImpact".
	ModifiedIntegrityImpact *ModifiedCiaType `json:"modifiedIntegrityImpact,omitempty,omitzero"`

	// ModifiedPrivilegesRequired corresponds to the JSON schema field
	// "modifiedPrivilegesRequired".
	ModifiedPrivilegesRequired *ModifiedPrivilegesRequiredType `json:"modifiedPrivilegesRequired,omitempty,omitzero"`

	// ModifiedScope corresponds to the JSON schema field "modifiedScope".
	ModifiedScope *ModifiedScopeType `json:"modifiedScope,omitempty,omitzero"`

	// ModifiedUserInteraction corresponds to the JSON schema field
	// "modifiedUserInteraction".
	ModifiedUserInteraction *ModifiedUserInteractionType `json:"modifiedUserInteraction,omitempty,omitzero"`

	// PrivilegesRequired corresponds to the JSON schema field "privilegesRequired".
	PrivilegesRequired *PrivilegesRequiredType `json:"privilegesRequired,omitempty,omitzero"`

	// RemediationLevel corresponds to the JSON schema field "remediationLevel".
	RemediationLevel *RemediationLevelType `json:"remediationLevel,omitempty,omitzero"`

	// ReportConfidence corresponds to the JSON schema field "reportConfidence".
	ReportConfidence *ConfidenceType `json:"reportConfidence,omitempty,omitzero"`

	// Scope corresponds to the JSON schema field "scope".
	Scope *ScopeType `json:"scope,omitempty,omitzero"`

	// TemporalScore corresponds to the JSON schema field "temporalScore".
	TemporalScore *ScoreType `json:"temporalScore,omitempty,omitzero"`

	// TemporalSeverity corresponds to the JSON schema field "temporalSeverity".
	TemporalSeverity *SeverityType `json:"temporalSeverity,omitempty,omitzero"`

	// UserInteraction corresponds to the JSON schema field "userInteraction".
	UserInteraction *UserInteractionType `json:"userInteraction,omitempty,omitzero"`

	// VectorString corresponds to the JSON schema field "vectorString".
	VectorString string `json:"vectorString"`

	// CVSS Version
	Version CVSSV31Version `json:"version"`
}

type CVSSV31Version string

const CVSSV31VersionA31 CVSSV31Version = "3.1"

type CiaRequirementType string

const CiaRequirementTypeHIGH CiaRequirementType = "HIGH"
const CiaRequirementTypeLOW CiaRequirementType = "LOW"
const CiaRequirementTypeMEDIUM CiaRequirementType = "MEDIUM"
const CiaRequirementTypeNOTDEFINED CiaRequirementType = "NOT_DEFINED"

type CiaType string

const CiaTypeCOMPLETE CiaType = "COMPLETE"
const CiaTypeNONE CiaType = "NONE"
const CiaTypePARTIAL CiaType = "PARTIAL"

type CiaType_1 string

const CiaType_1_HIGH CiaType_1 = "HIGH"
const CiaType_1_LOW CiaType_1 = "LOW"
const CiaType_1_NONE CiaType_1 = "NONE"

type CollateralDamagePotentialType string

const CollateralDamagePotentialTypeHIGH CollateralDamagePotentialType = "HIGH"
const CollateralDamagePotentialTypeLOW CollateralDamagePotentialType = "LOW"
const CollateralDamagePotentialTypeLOWMEDIUM CollateralDamagePotentialType = "LOW_MEDIUM"
const CollateralDamagePotentialTypeMEDIUMHIGH CollateralDamagePotentialType = "MEDIUM_HIGH"
const CollateralDamagePotentialTypeNONE CollateralDamagePotentialType = "NONE"
const CollateralDamagePotentialTypeNOTDEFINED CollateralDamagePotentialType = "NOT_DEFINED"

type ConfidenceType string

const ConfidenceTypeCONFIRMED ConfidenceType = "CONFIRMED"
const ConfidenceTypeNOTDEFINED ConfidenceType = "NOT_DEFINED"
const ConfidenceTypeREASONABLE ConfidenceType = "REASONABLE"
const ConfidenceTypeUNKNOWN ConfidenceType = "UNKNOWN"

type ExploitCodeMaturityType string

const ExploitCodeMaturityTypeFUNCTIONAL ExploitCodeMaturityType = "FUNCTIONAL"
const ExploitCodeMaturityTypeHIGH ExploitCodeMaturityType = "HIGH"
const ExploitCodeMaturityTypeNOTDEFINED ExploitCodeMaturityType = "NOT_DEFINED"
const ExploitCodeMaturityTypePROOFOFCONCEPT ExploitCodeMaturityType = "PROOF_OF_CONCEPT"
const ExploitCodeMaturityTypeUNPROVEN ExploitCodeMaturityType = "UNPROVEN"

type ExploitabilityType string

const ExploitabilityTypeFUNCTIONAL ExploitabilityType = "FUNCTIONAL"
const ExploitabilityTypeHIGH ExploitabilityType = "HIGH"
const ExploitabilityTypeNOTDEFINED ExploitabilityType = "NOT_DEFINED"
const ExploitabilityTypePROOFOFCONCEPT ExploitabilityType = "PROOF_OF_CONCEPT"
const ExploitabilityTypeUNPROVEN ExploitabilityType = "UNPROVEN"

type ModifiedAttackComplexityType string

const ModifiedAttackComplexityTypeHIGH ModifiedAttackComplexityType = "HIGH"
const ModifiedAttackComplexityTypeLOW ModifiedAttackComplexityType = "LOW"
const ModifiedAttackComplexityTypeNOTDEFINED ModifiedAttackComplexityType = "NOT_DEFINED"

type ModifiedAttackVectorType string

const ModifiedAttackVectorTypeADJACENTNETWORK ModifiedAttackVectorType = "ADJACENT_NETWORK"
const ModifiedAttackVectorTypeLOCAL ModifiedAttackVectorType = "LOCAL"
const ModifiedAttackVectorTypeNETWORK ModifiedAttackVectorType = "NETWORK"
const ModifiedAttackVectorTypeNOTDEFINED ModifiedAttackVectorType = "NOT_DEFINED"
const ModifiedAttackVectorTypePHYSICAL ModifiedAttackVectorType = "PHYSICAL"

type ModifiedCiaType string

const ModifiedCiaTypeHIGH ModifiedCiaType = "HIGH"
const ModifiedCiaTypeLOW ModifiedCiaType = "LOW"
const ModifiedCiaTypeNONE ModifiedCiaType = "NONE"
const ModifiedCiaTypeNOTDEFINED ModifiedCiaType = "NOT_DEFINED"

type ModifiedPrivilegesRequiredType string

const ModifiedPrivilegesRequiredTypeHIGH ModifiedPrivilegesRequiredType = "HIGH"
const ModifiedPrivilegesRequiredTypeLOW ModifiedPrivilegesRequiredType = "LOW"
const ModifiedPrivilegesRequiredTypeNONE ModifiedPrivilegesRequiredType = "NONE"
const ModifiedPrivilegesRequiredTypeNOTDEFINED ModifiedPrivilegesRequiredType = "NOT_DEFINED"

type ModifiedScopeType string

const ModifiedScopeTypeCHANGED ModifiedScopeType = "CHANGED"
const ModifiedScopeTypeNOTDEFINED ModifiedScopeType = "NOT_DEFINED"
const ModifiedScopeTypeUNCHANGED ModifiedScopeType = "UNCHANGED"

type ModifiedUserInteractionType string

const ModifiedUserInteractionTypeNONE ModifiedUserInteractionType = "NONE"
const ModifiedUserInteractionTypeNOTDEFINED ModifiedUserInteractionType = "NOT_DEFINED"
const ModifiedUserInteractionTypeREQUIRED ModifiedUserInteractionType = "REQUIRED"

type PrivilegesRequiredType string

const PrivilegesRequiredTypeHIGH PrivilegesRequiredType = "HIGH"
const PrivilegesRequiredTypeLOW PrivilegesRequiredType = "LOW"
const PrivilegesRequiredTypeNONE PrivilegesRequiredType = "NONE"

type RemediationLevelType string

const RemediationLevelTypeNOTDEFINED RemediationLevelType = "NOT_DEFINED"
const RemediationLevelTypeOFFICIALFIX RemediationLevelType = "OFFICIAL_FIX"
const RemediationLevelTypeTEMPORARYFIX RemediationLevelType = "TEMPORARY_FIX"
const RemediationLevelTypeUNAVAILABLE RemediationLevelType = "UNAVAILABLE"
const RemediationLevelTypeWORKAROUND RemediationLevelType = "WORKAROUND"

type ReportConfidenceType string

const ReportConfidenceTypeCONFIRMED ReportConfidenceType = "CONFIRMED"
const ReportConfidenceTypeNOTDEFINED ReportConfidenceType = "NOT_DEFINED"
const ReportConfidenceTypeUNCONFIRMED ReportConfidenceType = "UNCONFIRMED"
const ReportConfidenceTypeUNCORROBORATED ReportConfidenceType = "UNCORROBORATED"

type ScopeType string

const ScopeTypeCHANGED ScopeType = "CHANGED"
const ScopeTypeUNCHANGED ScopeType = "UNCHANGED"

type ScoreType float64

type SeverityType string

const SeverityTypeCRITICAL SeverityType = "CRITICAL"
const SeverityTypeHIGH SeverityType = "HIGH"
const SeverityTypeLOW SeverityType = "LOW"
const SeverityTypeMEDIUM SeverityType = "MEDIUM"
const SeverityTypeNONE SeverityType = "NONE"

type TargetDistributionType string

const TargetDistributionTypeHIGH TargetDistributionType = "HIGH"
const TargetDistributionTypeLOW TargetDistributionType = "LOW"
const TargetDistributionTypeMEDIUM TargetDistributionType = "MEDIUM"
const TargetDistributionTypeNONE TargetDistributionType = "NONE"
const TargetDistributionTypeNOTDEFINED TargetDistributionType = "NOT_DEFINED"

type UserInteractionType string

const UserInteractionTypeNONE UserInteractionType = "NONE"
const UserInteractionTypeREQUIRED UserInteractionType = "REQUIRED"
