# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

"""Save the schema graph as individual files with an embedded URI index."""

import json
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urldefrag, urljoin, urlsplit
from urllib.request import urlopen

HTTP_TIMEOUT_SECONDS = 30
GENERATED_HEADER = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>
// Code generated by internal/generate/bundle_schema.py. DO NOT EDIT.

package v21

import "embed"

"""


def fetch(uri: str) -> bytes:
    with urlopen(uri, timeout=HTTP_TIMEOUT_SECONDS) as response:
        return response.read()


def read_source(source: str) -> bytes:
    if source.startswith(("https://", "http://")):
        return fetch(source)
    return Path(source).read_bytes()


def decode_document(data: bytes) -> Any:
    return json.loads(data)


def schema_identifier(document: Any) -> str:
    if not isinstance(document, dict):
        msg = "schema is not an object"
        raise ValueError(msg)
    identifier = document.get("$id", document.get("id"))
    if not isinstance(identifier, str):
        msg = "schema has no identifier"
        raise ValueError(msg)
    return identifier


def strip_fragment(uri: str) -> str:
    return urldefrag(uri).url


def references(value: Any, base_uri: str) -> list[str]:
    found: list[str] = []
    if isinstance(value, list):
        for item in value:
            found.extend(references(item, base_uri))
    elif isinstance(value, dict):
        identifier = value.get("$id", value.get("id"))
        if isinstance(identifier, str):
            base_uri = urljoin(base_uri, identifier)
        for key, item in value.items():
            if key in {"$ref", "$schema"} and isinstance(item, str):
                found.append(urljoin(base_uri, item))
            found.extend(references(item, base_uri))
    return found


def should_skip(uri: str) -> bool:
    return (
        not uri
        or uri.startswith("#")
        or uri.startswith("http://json-schema.org/")
        or uri.startswith("https://json-schema.org/")
    )


def add_resource(bundled: dict[str, bytes], data: bytes) -> Any:
    document = decode_document(data)
    bundled[strip_fragment(schema_identifier(document))] = data
    return document


def add_references(bundled: dict[str, bytes], document: Any) -> None:
    base_uri = schema_identifier(document)
    for reference in references(document, base_uri):
        uri = strip_fragment(reference)
        if should_skip(uri) or uri in bundled:
            continue
        remote = fetch(uri)
        bundled[uri] = remote
        remote_document = add_resource(bundled, remote)
        try:
            add_references(bundled, remote_document)
        except Exception as error:
            msg = f"load references from {uri}: {error}"
            raise RuntimeError(msg) from error


def resource_path(identifier: str) -> str:
    if identifier == "urn:gocsaf:schema:csaf:2.1:rolie-feed":
        return "schema/rolie-feed.json"
    uri = urlsplit(identifier)
    parts = uri.path.lstrip("/").split("/")
    if uri.scheme not in {"http", "https"} or not uri.netloc or any(part in {"", ".", ".."} for part in parts):
        msg = f"unsupported schema identifier: {identifier}"
        raise ValueError(msg)
    if identifier.startswith("https://docs.oasis-open.org/csaf/csaf/v2.1/schema/"):
        return "schema/" + parts[-1]
    # Revision queries are URI aliases; collisions are checked before writing.
    return "schema/external/" + uri.netloc + "/" + "/".join(parts)


def write_bundle(path: Path, bundled: dict[str, bytes]) -> None:
    resources: dict[str, Any] = {}
    paths: dict[str, str] = {}
    for uri, data in sorted(bundled.items()):
        document = decode_document(data)
        filename = resource_path(schema_identifier(document))
        if filename in resources and resources[filename] != document:
            msg = f"different schemas map to {filename}"
            raise ValueError(msg)
        resources[filename] = document
        paths[uri] = filename

    for filename, document in sorted(resources.items()):
        destination = path.parent / filename
        destination.parent.mkdir(parents=True, exist_ok=True)
        # Preserve formatting of maintained inputs such as the ROLIE schema.
        if destination.exists() and json.loads(destination.read_bytes()) == document:
            continue
        destination.write_text(
            json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    directives = "".join(f"//go:embed {filename}\n" for filename in sorted(resources))
    entries = "".join(f"\t{json.dumps(uri)}: {json.dumps(filename)},\n" for uri, filename in paths.items())
    path.write_text(
        GENERATED_HEADER
        + directives
        + "var schemaFiles embed.FS\n\n"
        + "var schemaPaths = map[string]string{\n"
        + entries
        + "}\n",
        encoding="utf-8",
    )


def bundle_schemas(output: Path, sources: list[str]) -> None:
    bundled: dict[str, bytes] = {}
    documents = [add_resource(bundled, read_source(source)) for source in sources]
    # Follow the complete graph now so runtime validation never uses the network.
    for document in documents:
        add_references(bundled, document)
    write_bundle(output, bundled)


def main(arguments: list[str]) -> int:
    if len(arguments) < 2:
        print(
            "usage: bundle-schema <output Go file> <schema> [schema ...]",
            file=sys.stderr,
        )
        return 2
    bundle_schemas(Path(arguments[0]), arguments[1:])
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except Exception as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
