# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

"""Apply narrow, fail-fast repairs to go-jsonschema model output."""

import sys
from pathlib import Path

GENERATED_CVSS_V3_FIELD = '\tCVSSV3 interface{} `json:"cvss_v3,omitempty,omitzero"`'
TYPED_CVSS_V3_FIELD = '\tCVSSV3 CVSSV3 `json:"cvss_v3,omitempty,omitzero"`'
GENERATED_SSVC_V2_SCHEMA_VERSION_FIELD = '\tSchemaVersion string `json:"schemaVersion"`'
TYPED_SSVC_V2_SCHEMA_VERSION_FIELD = '\tSchemaVersion SSVCV2SchemaVersion `json:"schemaVersion"`'

# Exact source matches are intentional. If go-jsonschema changes its output,
# generation must fail so each repair can be reviewed instead of silently lost.
REPLACEMENTS = {
    GENERATED_CVSS_V3_FIELD: TYPED_CVSS_V3_FIELD,
    GENERATED_SSVC_V2_SCHEMA_VERSION_FIELD: TYPED_SSVC_V2_SCHEMA_VERSION_FIELD,
    '\tBaseScore NoneScoreType `json:"baseScore"`': ('\tBaseScore float64 `json:"baseScore"`'),
    '\tBaseSeverity NoneSeverityType `json:"baseSeverity"`': ('\tBaseSeverity CVSSV40Severity `json:"baseSeverity"`'),
}

GENERATED_HEADER = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
// Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

// Code generated by go-jsonschema and internal/generate/prepare_model.py. DO NOT EDIT.

"""


def prepare_model(path: Path) -> tuple[dict[str, int], int]:
    output_lines: list[str] = []
    replacement_counts = dict.fromkeys(REPLACEMENTS, 0)
    date_time_replacements = 0

    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith("// Code generated"):
            continue
        if line == 'import "time"':
            continue
        # time.Time normalizes JSON during a round trip and rejects lowercase
        # RFC 3339 separators. DateTime deliberately retains the source text.
        if "time.Time" in line:
            date_time_replacements += line.count("time.Time")
            line = line.replace("time.Time", "DateTime")
        if line in REPLACEMENTS:
            replacement_counts[line] += 1
            line = REPLACEMENTS[line]
        output_lines.append(line)

    path.write_text(
        GENERATED_HEADER + "\n".join(output_lines) + "\n",
        encoding="utf-8",
    )
    return replacement_counts, date_time_replacements


def prepare_models(paths: list[Path]) -> None:
    replacement_counts = dict.fromkeys(REPLACEMENTS, 0)
    date_time_replacements = 0
    for path in paths:
        file_counts, file_date_time_replacements = prepare_model(path)
        for generated, count in file_counts.items():
            replacement_counts[generated] += count
        date_time_replacements += file_date_time_replacements

    for generated, count in replacement_counts.items():
        if count != 1:
            msg = f"expected one occurrence of {generated!r}, replaced {count}"
            raise ValueError(msg)
    if date_time_replacements == 0:
        msg = "generated models contain no date-time fields"
        raise ValueError(msg)


def main(arguments: list[str]) -> int:
    if not arguments:
        print("usage: prepare-model <generated Go file> ...", file=sys.stderr)
        return 2
    prepare_models([Path(argument) for argument in arguments])
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main(sys.argv[1:]))
    except Exception as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
