# SPDX-License-Identifier: Apache-2.0

"""Apply the checked 2.0 model repairs after go-jsonschema generation."""

import sys
from pathlib import Path

HEADER = """// SPDX-License-Identifier: Apache-2.0

// Code generated by go-jsonschema and internal/generate/prepare_v20_model.py. DO NOT EDIT.

"""
CVSS_FIELD = '\tCVSSV3 interface{} `json:"cvss_v3,omitempty,omitzero"`'
TYPED_CVSS_FIELD = '\tCVSSV3 CVSSV3 `json:"cvss_v3,omitempty,omitzero"`'


def prepare(paths: list[Path]) -> None:
    cvss_fields = 0
    date_time_fields = 0
    for path in paths:
        lines: list[str] = []
        for line in path.read_text().splitlines():
            if line.startswith("// Code generated") or line == 'import "time"':
                continue
            cvss_fields += line.count(CVSS_FIELD)
            line = line.replace(CVSS_FIELD, TYPED_CVSS_FIELD)
            date_time_fields += line.count("time.Time")
            line = line.replace("time.Time", "DateTime")
            lines.append(line.replace("\u2014", "-").replace("\u2019", "'"))
        path.write_text(HEADER + "\n".join(lines) + "\n")
    if cvss_fields != 1 or date_time_fields == 0:
        msg = f"unexpected generator output: CVSS fields={cvss_fields}, date-time fields={date_time_fields}"
        raise ValueError(msg)


def main(arguments: list[str]) -> int:
    if not arguments:
        print("usage: prepare_v20_model.py <generated Go file> ...", file=sys.stderr)
        return 2
    prepare([Path(argument) for argument in arguments])
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
